/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package projectkasir;

import Koneksi.Config;
import java.awt.Color;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author Izzul Islam Ramadhan
 */
public class Form_GantiPassword extends javax.swing.JPanel {

    /**
     * Creates new form Form_GantiPassword2
     */
    public Form_GantiPassword() {
        initComponents();
        setBackground(new Color(255,255,255));
        btn_hide1.setVisible(true);
        btn_hide2.setVisible(true);
        btn_hide3.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_show1 = new javax.swing.JLabel();
        btn_hide1 = new javax.swing.JLabel();
        txtpasswordlama = new javax.swing.JPasswordField();
        btn_hide2 = new javax.swing.JLabel();
        btn_show2 = new javax.swing.JLabel();
        txtpasswordbaru = new javax.swing.JPasswordField();
        btn_show3 = new javax.swing.JLabel();
        btn_hide3 = new javax.swing.JLabel();
        txtkonfirmasi = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnsubmit = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(10, 104, 71));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Change Password");

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Settings > Change Password");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(637, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(381, 381, 381)
                .addComponent(jLabel11)
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                .addContainerGap())
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dubai", 0, 24)); // NOI18N
        jLabel3.setText("Password Baru");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 327, 257, 50));

        jLabel4.setFont(new java.awt.Font("Dubai", 0, 24)); // NOI18N
        jLabel4.setText("Konfirmasi Password Baru");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 395, -1, 50));

        btn_show1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hidden.png"))); // NOI18N
        btn_show1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_show1MouseClicked(evt);
            }
        });
        add(btn_show1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 256, 50, 50));

        btn_hide1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/show.png"))); // NOI18N
        btn_hide1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_hide1MouseClicked(evt);
            }
        });
        add(btn_hide1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 256, 50, 50));

        txtpasswordlama.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtpasswordlama.setForeground(new java.awt.Color(102, 102, 102));
        txtpasswordlama.setText("PasswordLama");
        txtpasswordlama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpasswordlamaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpasswordlamaFocusLost(evt);
            }
        });
        txtpasswordlama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpasswordlamaKeyTyped(evt);
            }
        });
        add(txtpasswordlama, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 259, 500, 50));

        btn_hide2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/show.png"))); // NOI18N
        btn_hide2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_hide2MouseClicked(evt);
            }
        });
        add(btn_hide2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 330, 50, 50));

        btn_show2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hidden.png"))); // NOI18N
        btn_show2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_show2MouseClicked(evt);
            }
        });
        add(btn_show2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 330, 50, 50));

        txtpasswordbaru.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtpasswordbaru.setForeground(new java.awt.Color(102, 102, 102));
        txtpasswordbaru.setText("PasswordBaru");
        txtpasswordbaru.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpasswordbaruFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpasswordbaruFocusLost(evt);
            }
        });
        txtpasswordbaru.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpasswordbaruKeyTyped(evt);
            }
        });
        add(txtpasswordbaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 327, 500, 50));

        btn_show3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hidden.png"))); // NOI18N
        btn_show3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_show3MouseClicked(evt);
            }
        });
        add(btn_show3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 400, 50, 40));

        btn_hide3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/show.png"))); // NOI18N
        btn_hide3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_hide3MouseClicked(evt);
            }
        });
        add(btn_hide3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 400, 50, 40));

        txtkonfirmasi.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtkonfirmasi.setForeground(new java.awt.Color(102, 102, 102));
        txtkonfirmasi.setText("KonfirmasiPasswordBaru");
        txtkonfirmasi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtkonfirmasiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtkonfirmasiFocusLost(evt);
            }
        });
        txtkonfirmasi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtkonfirmasiKeyTyped(evt);
            }
        });
        add(txtkonfirmasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 395, 500, 50));

        jLabel1.setFont(new java.awt.Font("Dubai", 0, 24)); // NOI18N
        jLabel1.setText("Username");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 189, 257, 50));

        txtusername.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtusername.setForeground(new java.awt.Color(102, 102, 102));
        txtusername.setText("Username");
        txtusername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtusernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtusernameFocusLost(evt);
            }
        });
        txtusername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtusernameKeyTyped(evt);
            }
        });
        add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 187, 500, 52));

        jLabel2.setFont(new java.awt.Font("Dubai", 0, 24)); // NOI18N
        jLabel2.setText("Password Lama");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 259, 257, 50));

        btnsubmit.setBackground(new java.awt.Color(0, 153, 0));
        btnsubmit.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        btnsubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnsubmit.setText("Submit");
        btnsubmit.setBorder(null);
        btnsubmit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsubmitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsubmitMouseExited(evt);
            }
        });
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });
        add(btnsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 559, 150, 60));

        btncancel.setBackground(new java.awt.Color(204, 0, 0));
        btncancel.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        btncancel.setForeground(new java.awt.Color(255, 255, 255));
        btncancel.setText("Cancel");
        btncancel.setBorder(null);
        btncancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncancelMouseExited(evt);
            }
        });
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        add(btncancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 559, 150, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void txtpasswordlamaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpasswordlamaFocusGained
        // TODO add your handling code here:
        String user = txtpasswordlama.getText();
        if (user.equals("PasswordLama")) {
            txtpasswordlama.setText("");
        }
    }//GEN-LAST:event_txtpasswordlamaFocusGained

    private void txtpasswordlamaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpasswordlamaFocusLost
        // TODO add your handling code here:
        String user = txtpasswordlama.getText();
        if (user.equals("") || user.equals("PasswordLama")) {
            txtpasswordlama.setText("PasswordLama");
            txtpasswordlama.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_txtpasswordlamaFocusLost

    private void txtpasswordbaruFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpasswordbaruFocusGained
        // TODO add your handling code here:
        String user = txtpasswordbaru.getText();
        if (user.equals("PasswordBaru")) {
            txtpasswordbaru.setText("");
        }
    }//GEN-LAST:event_txtpasswordbaruFocusGained

    private void txtpasswordbaruFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpasswordbaruFocusLost
        // TODO add your handling code here:
        String user = txtpasswordbaru.getText();
        if (user.equals("") || user.equals("PasswordBaru")) {
            txtpasswordbaru.setText("PasswordBaru");
            txtpasswordbaru.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_txtpasswordbaruFocusLost

    private void txtkonfirmasiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtkonfirmasiFocusGained
        // TODO add your handling code here:
        String user = txtkonfirmasi.getText();
        if (user.equals("KonfirmasiPasswordBaru")) {
            txtkonfirmasi.setText("");
        }
    }//GEN-LAST:event_txtkonfirmasiFocusGained

    private void txtkonfirmasiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtkonfirmasiFocusLost
        // TODO add your handling code here:
        String user = txtkonfirmasi.getText();
        if (user.equals("") || user.equals("KonfirmasiPasswordBaru")) {
            txtkonfirmasi.setText("KonfirmasiPasswordBaru");
            txtkonfirmasi.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_txtkonfirmasiFocusLost

    private void txtusernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtusernameFocusGained
        // TODO add your handling code here:
        String user = txtusername.getText();
        if (user.equals("Username")) {
            txtusername.setText("");
        }
    }//GEN-LAST:event_txtusernameFocusGained

    private void txtusernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtusernameFocusLost
        // TODO add your handling code here:
        String user = txtusername.getText();
        if (user.equals("") || user.equals("Username")) {
            txtusername.setText("Username");
            txtusername.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_txtusernameFocusLost

    private void btnsubmitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsubmitMouseEntered
        // TODO add your handling code here:
        btnsubmit.setBackground(new Color(0,102,0));
    }//GEN-LAST:event_btnsubmitMouseEntered

    private void btnsubmitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsubmitMouseExited
        // TODO add your handling code here:
        btnsubmit.setBackground(new Color(0,153,0));
    }//GEN-LAST:event_btnsubmitMouseExited

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        // TODO add your handling code here:
        if (txtusername.getText().equals("Username") || txtpasswordlama.getText().equals("PasswordLama") 
                || txtpasswordbaru.getText().equals("PasswordBaru") || txtkonfirmasi.getText().equals("KonfirmasiPasswordBaru") ) {
        JOptionPane.showMessageDialog(this, "Silahkan isi data terlebih dahulu !");
        return;
        }
        
        if (txtkonfirmasi.getText().equals(txtpasswordbaru.getText())) {
        try {
        String sql = "SELECT * FROM akun WHERE username='"+txtusername.getText()
                    +"'AND password='"+txtpasswordlama.getText()+"'";
            Connection conn= Config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery(sql);
        if (!rs.next()) {
            JOptionPane.showMessageDialog(this, "Akun tidak ditemukan! Coba periksa apakah username atau password lama yang diiinputkan sudah benar!");
            return;
        }
        
        String sqlUpdatePassword = "UPDATE akun SET password = ? WHERE username = ?";
        java.sql.PreparedStatement pstUpdatePassword = conn.prepareStatement(sqlUpdatePassword);
        pstUpdatePassword.setString(1, txtkonfirmasi.getText());
        pstUpdatePassword.setString(2, txtusername.getText());
        pstUpdatePassword.execute();

        JOptionPane.showMessageDialog(null, "Password Berhasil Diubah!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
} else {
    JOptionPane.showMessageDialog(this, "Konfirmasi password tidak sesuai");
}
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void btncancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncancelMouseEntered
        // TODO add your handling code here:
        btncancel.setBackground(new Color(153,0,0));
    }//GEN-LAST:event_btncancelMouseEntered

    private void btncancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncancelMouseExited
        // TODO add your handling code here:
        btncancel.setBackground(new Color(204,0,0));
    }//GEN-LAST:event_btncancelMouseExited

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
        txtusername.setText("Username");
        txtpasswordbaru.setText("PasswordBaru");
        txtpasswordlama.setText("PasswordLama");
        txtkonfirmasi.setText("KonfirmasiPasswordBaru");
        txtusername.setForeground(new Color(102,102,102));
        txtpasswordlama.setForeground(new Color(102,102,102));
        txtpasswordbaru.setForeground(new Color(102,102,102));
        txtkonfirmasi.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_btncancelActionPerformed

    private void txtusernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusernameKeyTyped
        // TODO add your handling code here:
        txtusername.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_txtusernameKeyTyped

    private void txtpasswordlamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasswordlamaKeyTyped
        // TODO add your handling code here:
        txtpasswordlama.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_txtpasswordlamaKeyTyped

    private void txtpasswordbaruKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasswordbaruKeyTyped
        // TODO add your handling code here:
        txtpasswordbaru.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_txtpasswordbaruKeyTyped

    private void txtkonfirmasiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtkonfirmasiKeyTyped
        // TODO add your handling code here:
        txtkonfirmasi.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_txtkonfirmasiKeyTyped

    private void btn_show1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_show1MouseClicked
        // TODO add your handling code here:
        btn_show1.setVisible(false);
        btn_hide1.setVisible(true);
        txtpasswordlama.setEchoChar((char)0);
    }//GEN-LAST:event_btn_show1MouseClicked

    private void btn_hide1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hide1MouseClicked
        // TODO add your handling code here:
        btn_show1.setVisible(true);
        btn_hide1.setVisible(false);
        txtpasswordlama.setEchoChar('*');
    }//GEN-LAST:event_btn_hide1MouseClicked

    private void btn_hide2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hide2MouseClicked
        // TODO add your handling code here:
        btn_show2.setVisible(true);
        btn_hide2.setVisible(false);
        txtpasswordbaru.setEchoChar('*');
    }//GEN-LAST:event_btn_hide2MouseClicked

    private void btn_show2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_show2MouseClicked
        // TODO add your handling code here:
        btn_show2.setVisible(false);
        btn_hide2.setVisible(true);
        txtpasswordbaru.setEchoChar((char)0);
    }//GEN-LAST:event_btn_show2MouseClicked

    private void btn_show3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_show3MouseClicked
        // TODO add your handling code here:
        btn_show3.setVisible(false);
        btn_hide3.setVisible(true);
        txtkonfirmasi.setEchoChar((char)0);
    }//GEN-LAST:event_btn_show3MouseClicked

    private void btn_hide3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hide3MouseClicked
        // TODO add your handling code here:
        btn_show3.setVisible(true);
        btn_hide3.setVisible(false);
        txtkonfirmasi.setEchoChar('*');
    }//GEN-LAST:event_btn_hide3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_hide1;
    private javax.swing.JLabel btn_hide2;
    private javax.swing.JLabel btn_hide3;
    private javax.swing.JLabel btn_show1;
    private javax.swing.JLabel btn_show2;
    private javax.swing.JLabel btn_show3;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField txtkonfirmasi;
    private javax.swing.JPasswordField txtpasswordbaru;
    private javax.swing.JPasswordField txtpasswordlama;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
