/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectkasir;

import Koneksi.Config;
import java.awt.Color;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author Izzul Islam Ramadhan
 */
public class LupaPassword extends javax.swing.JFrame {

    /**
     * Creates new form LupaPassword
     */
    public LupaPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnkembali = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnlanjut = new javax.swing.JButton();
        btnregister2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txttelepon = new javax.swing.JTextField();
        jpanelgradient_11 = new jpanelgradient.jpanelgradient_1();
        jLabel16 = new javax.swing.JLabel();
        pn_btnclose3 = new javax.swing.JPanel();
        btnclose2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 3, 14)); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(769, 527));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnkembali.setBackground(new java.awt.Color(204, 0, 0));
        btnkembali.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        btnkembali.setForeground(new java.awt.Color(255, 255, 255));
        btnkembali.setText("Kembali");
        btnkembali.setBorder(null);
        btnkembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnkembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnkembaliMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnkembaliMouseExited(evt);
            }
        });
        btnkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkembaliActionPerformed(evt);
            }
        });
        jPanel3.add(btnkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 150, 60));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Konfirmasi Password");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("No. Hp :");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 90, 40));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Masukkan No. Handphone");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 300, -1));

        btnlanjut.setBackground(new java.awt.Color(0, 153, 0));
        btnlanjut.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        btnlanjut.setForeground(new java.awt.Color(255, 255, 255));
        btnlanjut.setText("Lanjut");
        btnlanjut.setBorder(null);
        btnlanjut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlanjut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnlanjutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnlanjutMouseExited(evt);
            }
        });
        btnlanjut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlanjutActionPerformed(evt);
            }
        });
        jPanel3.add(btnlanjut, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 140, 60));

        btnregister2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnregister2.setForeground(new java.awt.Color(32, 136, 203));
        btnregister2.setText("Register");
        btnregister2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnregister2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnregister2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnregister2MouseExited(evt);
            }
        });
        jPanel3.add(btnregister2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 570, 80, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel7.setText("Belum memiliki akun?");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 570, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("yang sudah didaftarkan");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 270, -1));

        txttelepon.setBackground(new java.awt.Color(230, 227, 227));
        txttelepon.setFont(new java.awt.Font("Segoe UI Light", 1, 20)); // NOI18N
        txttelepon.setForeground(new java.awt.Color(102, 102, 102));
        txttelepon.setText("*Masukkan nomor handphone");
        txttelepon.setAutoscrolls(false);
        txttelepon.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txttelepon.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txttelepon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtteleponFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtteleponFocusLost(evt);
            }
        });
        txttelepon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtteleponMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtteleponMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtteleponMouseReleased(evt);
            }
        });
        txttelepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtteleponActionPerformed(evt);
            }
        });
        txttelepon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtteleponKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtteleponKeyTyped(evt);
            }
        });
        jPanel3.add(txttelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 330, 40));

        jpanelgradient_11.setColorEnd(new java.awt.Color(24, 252, 0));
        jpanelgradient_11.setColorStart(new java.awt.Color(0, 100, 0));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/konfirmasi.png"))); // NOI18N

        pn_btnclose3.setBackground(new java.awt.Color(0, 153, 0));
        pn_btnclose3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_btnclose3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_btnclose3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_btnclose3MouseExited(evt);
            }
        });

        btnclose2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Izzul Islam Ramadhan\\Downloads\\close.png")); // NOI18N
        btnclose2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnclose2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnclose2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnclose2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_btnclose3Layout = new javax.swing.GroupLayout(pn_btnclose3);
        pn_btnclose3.setLayout(pn_btnclose3Layout);
        pn_btnclose3Layout.setHorizontalGroup(
            pn_btnclose3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnclose3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnclose2)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        pn_btnclose3Layout.setVerticalGroup(
            pn_btnclose3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnclose3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnclose2)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout jpanelgradient_11Layout = new javax.swing.GroupLayout(jpanelgradient_11);
        jpanelgradient_11.setLayout(jpanelgradient_11Layout);
        jpanelgradient_11Layout.setHorizontalGroup(
            jpanelgradient_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelgradient_11Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelgradient_11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pn_btnclose3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpanelgradient_11Layout.setVerticalGroup(
            jpanelgradient_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelgradient_11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_btnclose3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpanelgradient_11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
            .addComponent(jpanelgradient_11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnkembaliMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkembaliMouseEntered
        // TODO add your handling code here:
        btnkembali.setBackground(new Color(153,0,0));
    }//GEN-LAST:event_btnkembaliMouseEntered

    private void btnkembaliMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkembaliMouseExited
        // TODO add your handling code here:
        btnkembali.setBackground(new Color(204,0,0));
    }//GEN-LAST:event_btnkembaliMouseExited

    private void btnkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkembaliActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Login2().setVisible(true);
    }//GEN-LAST:event_btnkembaliActionPerformed

    private void btnlanjutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlanjutMouseEntered
        // TODO add your handling code here:
        btnlanjut.setBackground(new Color(0,102,0));
    }//GEN-LAST:event_btnlanjutMouseEntered

    private void btnlanjutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlanjutMouseExited
        // TODO add your handling code here:
        btnlanjut.setBackground(new Color(0,153,0));
    }//GEN-LAST:event_btnlanjutMouseExited

    private void btnlanjutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlanjutActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "SELECT * FROM akun WHERE telp_user='"+txttelepon.getText()+"'";
            Connection conn= Config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery(sql);
            if(rs.next()){
                if(txttelepon.getText().equals(rs.getString("telp_user"))){
                    this.setVisible(false);
                    new PasswordBaru().setVisible(true);
                }
            }else{
                JOptionPane.showMessageDialog(null, "NOMOR HANDPHONE TIDAK DITEMUKAN");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnlanjutActionPerformed

    private void btnregister2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnregister2MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new PasswordToko().setVisible(true);
    }//GEN-LAST:event_btnregister2MouseClicked

    private void btnregister2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnregister2MouseEntered
        // TODO add your handling code here:
        btnregister2.setForeground(new Color(0,51,153));
    }//GEN-LAST:event_btnregister2MouseEntered

    private void btnregister2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnregister2MouseExited
        // TODO add your handling code here:
        btnregister2.setForeground(new Color(32,136,203));
    }//GEN-LAST:event_btnregister2MouseExited

    private void btnclose2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclose2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnclose2MouseClicked

    private void btnclose2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclose2MouseEntered
        // TODO add your handling code here:
        pn_btnclose3.setBackground(new Color(255,0,0));
        btnclose2.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_btnclose2MouseEntered

    private void btnclose2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclose2MouseExited
        // TODO add your handling code here:
        pn_btnclose3.setBackground(new Color(0,153,0));
        btnclose2.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btnclose2MouseExited

    private void pn_btnclose3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnclose3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_pn_btnclose3MouseClicked

    private void pn_btnclose3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnclose3MouseEntered
        // TODO add your handling code here:
        pn_btnclose3.setBackground(new Color(255,0,0));
        btnclose2.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_pn_btnclose3MouseEntered

    private void pn_btnclose3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnclose3MouseExited
        // TODO add your handling code here:
        pn_btnclose3.setBackground(new Color(0,153,0));
        btnclose2.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_pn_btnclose3MouseExited

    private void txtteleponFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtteleponFocusGained
        // TODO add your handling code here:
        String user = txttelepon.getText();
        if (user.equals("*Masukkan nomor handphone")) {
            txttelepon.setText("");
        }
    }//GEN-LAST:event_txtteleponFocusGained

    private void txtteleponFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtteleponFocusLost
        // TODO add your handling code here:
        String user = txttelepon.getText();
        if (user.equals("") || user.equals("*Masukkan nomor handphone")) {
            txttelepon.setText("*Masukkan nomor handphone");
            txttelepon.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_txtteleponFocusLost

    private void txtteleponMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtteleponMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtteleponMouseClicked

    private void txtteleponMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtteleponMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtteleponMousePressed

    private void txtteleponMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtteleponMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtteleponMouseReleased

    private void txtteleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtteleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtteleponActionPerformed

    private void txtteleponKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtteleponKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtteleponKeyPressed

    private void txtteleponKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtteleponKeyTyped
        // TODO add your handling code here:
        txttelepon.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_txtteleponKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LupaPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LupaPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LupaPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LupaPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LupaPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnclose2;
    private javax.swing.JButton btnkembali;
    private javax.swing.JButton btnlanjut;
    private javax.swing.JLabel btnregister2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private jpanelgradient.jpanelgradient_1 jpanelgradient_11;
    private javax.swing.JPanel pn_btnclose3;
    private javax.swing.JTextField txttelepon;
    // End of variables declaration//GEN-END:variables
}
