/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectkasir;

import Koneksi.Config;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
     * @author Izzul Islam Ramadhan
 */
public class MainMenu2 extends javax.swing.JFrame {
    
    int xx, xy;
    /**
     * Creates new form MainMenu
     */
    public MainMenu2() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        try {
            autofield();
        } catch (SQLException ex) {
            Logger.getLogger(MainMenu2.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ShowDayDateTime();
            }
        });
        timer.start();
    }
    
    private void ShowDayDateTime() {
        Calendar calendar = Calendar.getInstance();
        Date now = new Date();
        SimpleDateFormat formatHari = new SimpleDateFormat("EEEE",new Locale("in", "ID"));
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
        String hari = formatHari.format(calendar.getTime());
        String dateTime = dateFormat.format(now);
        lbltanggal.setText(hari+", "+dateTime);
    }
    
    private void autofield() throws SQLException {
        Connection conn = Config.configDB();
        String query = "SELECT username FROM log_akun WHERE id_log_akun = (SELECT MAX(id_log_akun) FROM log_akun)";

        try {
            PreparedStatement preparedStatement = conn.prepareStatement(query);
            ResultSet resultSet = preparedStatement.executeQuery();
            if (resultSet.next()) {
                String username = resultSet.getString("username");
                lblusername.setText(username);
            } else {
                System.out.println("");
            }
            resultSet.close();
            preparedStatement.close();
            conn.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        pn_kiri = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pn_btnPembelian = new javax.swing.JPanel();
        pn_line4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btn_pembelian = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pn_btnBarang = new javax.swing.JPanel();
        pn_line1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btn_barang = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pn_btnLaporan = new javax.swing.JPanel();
        pn_line5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnlappembelian = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        pn_btnDashboard = new javax.swing.JPanel();
        pn_line = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_dashboard = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pn_btnSupplier = new javax.swing.JPanel();
        pn_line2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btn_supplier = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        pn_btnLaporan1 = new javax.swing.JPanel();
        pn_line11 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        btnlappenjualan = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Master_Data = new javax.swing.JLabel();
        pn_btnLapStok = new javax.swing.JPanel();
        pn_line6 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        btnlapstok = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        Master_Data2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        pn_btnBarang1 = new javax.swing.JPanel();
        pn_line9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnpenjualan = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        Master_Data4 = new javax.swing.JLabel();
        pn_btnLapPenjualan = new javax.swing.JPanel();
        pn_line8 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        btnlapopname = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pn_kanan = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblusername = new javax.swing.JLabel();
        lbltanggal = new javax.swing.JLabel();
        lblusername1 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lbltanggal1 = new javax.swing.JLabel();
        lbltanggal2 = new javax.swing.JLabel();
        lbltanggal3 = new javax.swing.JLabel();
        btnsettings = new javax.swing.JButton();
        pn_btnminimize = new Custom.PanelCustom();
        btnminimize = new javax.swing.JLabel();
        pn_btnmaximize = new Custom.PanelCustom();
        btnmaximize = new javax.swing.JLabel();
        pn_btnclose = new Custom.PanelCustom();
        btnclose = new javax.swing.JLabel();
        pn_dasar = new javax.swing.JPanel();
        panelCustom1 = new javax.swing.JPanel();

        jLabel12.setText("jLabel12");

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 323, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kasir");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        pn_kiri.setBackground(new java.awt.Color(0, 91, 65));

        pn_btnPembelian.setBackground(new java.awt.Color(10, 104, 71));
        pn_btnPembelian.setForeground(new java.awt.Color(204, 204, 204));

        pn_line4.setBackground(new java.awt.Color(10, 104, 71));

        javax.swing.GroupLayout pn_line4Layout = new javax.swing.GroupLayout(pn_line4);
        pn_line4.setLayout(pn_line4Layout);
        pn_line4Layout.setHorizontalGroup(
            pn_line4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        pn_line4Layout.setVerticalGroup(
            pn_line4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel8.setForeground(new java.awt.Color(0, 51, 204));

        btn_pembelian.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btn_pembelian.setForeground(new java.awt.Color(204, 204, 204));
        btn_pembelian.setText("Pembelian");
        btn_pembelian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_pembelian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pembelianMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_pembelianMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_pembelianMouseExited(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pembelian.jpg.png"))); // NOI18N

        javax.swing.GroupLayout pn_btnPembelianLayout = new javax.swing.GroupLayout(pn_btnPembelian);
        pn_btnPembelian.setLayout(pn_btnPembelianLayout);
        pn_btnPembelianLayout.setHorizontalGroup(
            pn_btnPembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnPembelianLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_line4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_pembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_btnPembelianLayout.setVerticalGroup(
            pn_btnPembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_btnPembelianLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_btnPembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn_line4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_pembelian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                .addContainerGap())
        );

        pn_btnBarang.setBackground(new java.awt.Color(10, 104, 71));

        pn_line1.setBackground(new java.awt.Color(10, 104, 71));

        javax.swing.GroupLayout pn_line1Layout = new javax.swing.GroupLayout(pn_line1);
        pn_line1.setLayout(pn_line1Layout);
        pn_line1Layout.setHorizontalGroup(
            pn_line1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );
        pn_line1Layout.setVerticalGroup(
            pn_line1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel5.setForeground(new java.awt.Color(0, 51, 204));

        btn_barang.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btn_barang.setForeground(new java.awt.Color(204, 204, 204));
        btn_barang.setText("Barang");
        btn_barang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_barangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_barangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_barangMouseExited(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/barang.png"))); // NOI18N

        javax.swing.GroupLayout pn_btnBarangLayout = new javax.swing.GroupLayout(pn_btnBarang);
        pn_btnBarang.setLayout(pn_btnBarangLayout);
        pn_btnBarangLayout.setHorizontalGroup(
            pn_btnBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_line1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(16, 16, 16)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(btn_barang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_btnBarangLayout.setVerticalGroup(
            pn_btnBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_btnBarangLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel11)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(pn_btnBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_btnBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_barang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_line1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pn_btnLaporan.setBackground(new java.awt.Color(10, 104, 71));

        pn_line5.setBackground(new java.awt.Color(10, 104, 71));

        javax.swing.GroupLayout pn_line5Layout = new javax.swing.GroupLayout(pn_line5);
        pn_line5.setLayout(pn_line5Layout);
        pn_line5Layout.setHorizontalGroup(
            pn_line5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        pn_line5Layout.setVerticalGroup(
            pn_line5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel9.setForeground(new java.awt.Color(0, 51, 204));

        btnlappembelian.setBackground(new java.awt.Color(0, 0, 102));
        btnlappembelian.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btnlappembelian.setForeground(new java.awt.Color(204, 204, 204));
        btnlappembelian.setText("Pembelian");
        btnlappembelian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlappembelian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlappembelianMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnlappembelianMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnlappembelianMouseExited(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pembelian.jpg.png"))); // NOI18N

        javax.swing.GroupLayout pn_btnLaporanLayout = new javax.swing.GroupLayout(pn_btnLaporan);
        pn_btnLaporan.setLayout(pn_btnLaporanLayout);
        pn_btnLaporanLayout.setHorizontalGroup(
            pn_btnLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnLaporanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_line5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(btnlappembelian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        pn_btnLaporanLayout.setVerticalGroup(
            pn_btnLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_btnLaporanLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel17)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(pn_btnLaporanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_btnLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnlappembelian, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_line5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pn_btnDashboard.setBackground(new java.awt.Color(10, 104, 71));

        pn_line.setBackground(new java.awt.Color(10, 104, 71));
        pn_line.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_lineMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout pn_lineLayout = new javax.swing.GroupLayout(pn_line);
        pn_line.setLayout(pn_lineLayout);
        pn_lineLayout.setHorizontalGroup(
            pn_lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        pn_lineLayout.setVerticalGroup(
            pn_lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jLabel3.setForeground(new java.awt.Color(0, 51, 204));

        btn_dashboard.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btn_dashboard.setForeground(new java.awt.Color(204, 204, 204));
        btn_dashboard.setText("Dashboard");
        btn_dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseExited(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/dashboard (1).png"))); // NOI18N

        javax.swing.GroupLayout pn_btnDashboardLayout = new javax.swing.GroupLayout(pn_btnDashboard);
        pn_btnDashboard.setLayout(pn_btnDashboardLayout);
        pn_btnDashboardLayout.setHorizontalGroup(
            pn_btnDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_line, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(btn_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pn_btnDashboardLayout.setVerticalGroup(
            pn_btnDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_btnDashboardLayout.createSequentialGroup()
                .addComponent(pn_line, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
            .addComponent(btn_dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pn_btnSupplier.setBackground(new java.awt.Color(10, 104, 71));

        pn_line2.setBackground(new java.awt.Color(10, 104, 71));

        javax.swing.GroupLayout pn_line2Layout = new javax.swing.GroupLayout(pn_line2);
        pn_line2.setLayout(pn_line2Layout);
        pn_line2Layout.setHorizontalGroup(
            pn_line2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        pn_line2Layout.setVerticalGroup(
            pn_line2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel6.setForeground(new java.awt.Color(0, 51, 204));

        btn_supplier.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btn_supplier.setForeground(new java.awt.Color(204, 204, 204));
        btn_supplier.setText("Supplier");
        btn_supplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_supplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_supplierMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_supplierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_supplierMouseExited(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/supplier.jpg.png"))); // NOI18N

        javax.swing.GroupLayout pn_btnSupplierLayout = new javax.swing.GroupLayout(pn_btnSupplier);
        pn_btnSupplier.setLayout(pn_btnSupplierLayout);
        pn_btnSupplierLayout.setHorizontalGroup(
            pn_btnSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnSupplierLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_line2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(btn_supplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_btnSupplierLayout.setVerticalGroup(
            pn_btnSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_btnSupplierLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel13)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(pn_btnSupplierLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_btnSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_supplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_line2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 317, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        pn_btnLaporan1.setBackground(new java.awt.Color(10, 104, 71));
        pn_btnLaporan1.setPreferredSize(new java.awt.Dimension(163, 74));

        pn_line11.setBackground(new java.awt.Color(10, 104, 71));

        javax.swing.GroupLayout pn_line11Layout = new javax.swing.GroupLayout(pn_line11);
        pn_line11.setLayout(pn_line11Layout);
        pn_line11Layout.setHorizontalGroup(
            pn_line11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        pn_line11Layout.setVerticalGroup(
            pn_line11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel26.setForeground(new java.awt.Color(0, 51, 204));

        btnlappenjualan.setBackground(new java.awt.Color(0, 0, 102));
        btnlappenjualan.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btnlappenjualan.setForeground(new java.awt.Color(204, 204, 204));
        btnlappenjualan.setText("Penjualan");
        btnlappenjualan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlappenjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlappenjualanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnlappenjualanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnlappenjualanMouseExited(evt);
            }
        });

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/penjualan.jpg.png"))); // NOI18N

        javax.swing.GroupLayout pn_btnLaporan1Layout = new javax.swing.GroupLayout(pn_btnLaporan1);
        pn_btnLaporan1.setLayout(pn_btnLaporan1Layout);
        pn_btnLaporan1Layout.setHorizontalGroup(
            pn_btnLaporan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnLaporan1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_line11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addGap(18, 18, 18)
                .addComponent(btnlappenjualan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        pn_btnLaporan1Layout.setVerticalGroup(
            pn_btnLaporan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_btnLaporan1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel27)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pn_btnLaporan1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_btnLaporan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnlappenjualan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(pn_line11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(0, 91, 65));

        Master_Data.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        Master_Data.setForeground(new java.awt.Color(204, 204, 204));
        Master_Data.setText("    MASTER DATA");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Master_Data)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Master_Data)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pn_btnLapStok.setBackground(new java.awt.Color(10, 104, 71));

        pn_line6.setBackground(new java.awt.Color(10, 104, 71));

        javax.swing.GroupLayout pn_line6Layout = new javax.swing.GroupLayout(pn_line6);
        pn_line6.setLayout(pn_line6Layout);
        pn_line6Layout.setHorizontalGroup(
            pn_line6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        pn_line6Layout.setVerticalGroup(
            pn_line6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel18.setForeground(new java.awt.Color(0, 51, 204));

        btnlapstok.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btnlapstok.setForeground(new java.awt.Color(204, 204, 204));
        btnlapstok.setText("Stok");
        btnlapstok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlapstok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlapstokMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnlapstokMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnlapstokMouseExited(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/stok.png"))); // NOI18N

        javax.swing.GroupLayout pn_btnLapStokLayout = new javax.swing.GroupLayout(pn_btnLapStok);
        pn_btnLapStok.setLayout(pn_btnLapStokLayout);
        pn_btnLapStokLayout.setHorizontalGroup(
            pn_btnLapStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnLapStokLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_line6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(btnlapstok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        pn_btnLapStokLayout.setVerticalGroup(
            pn_btnLapStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_btnLapStokLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pn_btnLapStokLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_btnLapStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnlapstok, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(pn_line6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(0, 91, 65));

        Master_Data2.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        Master_Data2.setForeground(new java.awt.Color(204, 204, 204));
        Master_Data2.setText("    TRANSAKSI");

        jPanel8.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 313, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Master_Data2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(Master_Data2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pn_btnBarang1.setBackground(new java.awt.Color(10, 104, 71));

        pn_line9.setBackground(new java.awt.Color(10, 104, 71));

        javax.swing.GroupLayout pn_line9Layout = new javax.swing.GroupLayout(pn_line9);
        pn_line9.setLayout(pn_line9Layout);
        pn_line9Layout.setHorizontalGroup(
            pn_line9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );
        pn_line9Layout.setVerticalGroup(
            pn_line9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel7.setForeground(new java.awt.Color(0, 51, 204));

        btnpenjualan.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btnpenjualan.setForeground(new java.awt.Color(204, 204, 204));
        btnpenjualan.setText("Penjualan");
        btnpenjualan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnpenjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnpenjualanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnpenjualanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnpenjualanMouseExited(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/penjualan.jpg.png"))); // NOI18N

        javax.swing.GroupLayout pn_btnBarang1Layout = new javax.swing.GroupLayout(pn_btnBarang1);
        pn_btnBarang1.setLayout(pn_btnBarang1Layout);
        pn_btnBarang1Layout.setHorizontalGroup(
            pn_btnBarang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnBarang1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_line9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(16, 16, 16)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(btnpenjualan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_btnBarang1Layout.setVerticalGroup(
            pn_btnBarang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_btnBarang1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel14)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(pn_btnBarang1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_btnBarang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnpenjualan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_line9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(0, 91, 65));

        Master_Data4.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        Master_Data4.setForeground(new java.awt.Color(204, 204, 204));
        Master_Data4.setText("LAPORAN");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(Master_Data4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Master_Data4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pn_btnLapPenjualan.setBackground(new java.awt.Color(10, 104, 71));

        pn_line8.setBackground(new java.awt.Color(10, 104, 71));

        javax.swing.GroupLayout pn_line8Layout = new javax.swing.GroupLayout(pn_line8);
        pn_line8.setLayout(pn_line8Layout);
        pn_line8Layout.setHorizontalGroup(
            pn_line8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        pn_line8Layout.setVerticalGroup(
            pn_line8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel20.setForeground(new java.awt.Color(0, 51, 204));

        btnlapopname.setBackground(new java.awt.Color(204, 204, 204));
        btnlapopname.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btnlapopname.setForeground(new java.awt.Color(204, 204, 204));
        btnlapopname.setText("Opname");
        btnlapopname.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlapopname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlapopnameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnlapopnameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnlapopnameMouseExited(evt);
            }
        });

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/opname.png"))); // NOI18N

        javax.swing.GroupLayout pn_btnLapPenjualanLayout = new javax.swing.GroupLayout(pn_btnLapPenjualan);
        pn_btnLapPenjualan.setLayout(pn_btnLapPenjualanLayout);
        pn_btnLapPenjualanLayout.setHorizontalGroup(
            pn_btnLapPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnLapPenjualanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_line8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnlapopname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        pn_btnLapPenjualanLayout.setVerticalGroup(
            pn_btnLapPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_btnLapPenjualanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_btnLapPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn_line8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnlapopname, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addGroup(pn_btnLapPenjualanLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel21)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Kasir1-removebg-preview.png"))); // NOI18N

        javax.swing.GroupLayout pn_kiriLayout = new javax.swing.GroupLayout(pn_kiri);
        pn_kiri.setLayout(pn_kiriLayout);
        pn_kiriLayout.setHorizontalGroup(
            pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kiriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_btnSupplier, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_btnBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_btnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_btnBarang1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_btnPembelian, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_btnLaporan1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                    .addComponent(pn_btnLaporan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_btnLapPenjualan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_btnLapStok, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pn_kiriLayout.createSequentialGroup()
                        .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_kiriLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(pn_kiriLayout.createSequentialGroup()
                .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_kiriLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_kiriLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        pn_kiriLayout.setVerticalGroup(
            pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kiriLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(20, 20, 20)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(pn_btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_btnBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_btnSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(pn_btnBarang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_btnPembelian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(pn_btnLaporan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_btnLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_btnLapPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_btnLapStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        getContentPane().add(pn_kiri, java.awt.BorderLayout.LINE_START);

        pn_kanan.setBackground(new java.awt.Color(255, 255, 255));
        pn_kanan.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblusername.setFont(new java.awt.Font("Arial", 1, 26)); // NOI18N
        lblusername.setForeground(new java.awt.Color(102, 102, 102));
        lblusername.setText("Kasir");

        lbltanggal.setFont(new java.awt.Font("Arial", 1, 26)); // NOI18N
        lbltanggal.setForeground(new java.awt.Color(102, 102, 102));
        lbltanggal.setText("Tanggal");

        lblusername1.setFont(new java.awt.Font("Arial", 1, 26)); // NOI18N
        lblusername1.setForeground(new java.awt.Color(102, 102, 102));
        lblusername1.setText("Selamat datang,");

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        lbltanggal1.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        lbltanggal1.setText("|");

        lbltanggal2.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        lbltanggal2.setForeground(new java.awt.Color(102, 102, 102));
        lbltanggal2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cashier.png"))); // NOI18N

        lbltanggal3.setFont(new java.awt.Font("Arial", 1, 26)); // NOI18N
        lbltanggal3.setForeground(new java.awt.Color(102, 102, 102));
        lbltanggal3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/schedule.png"))); // NOI18N

        btnsettings.setBackground(new java.awt.Color(0, 102, 51));
        btnsettings.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnsettings.setForeground(new java.awt.Color(255, 255, 255));
        btnsettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/settings.png"))); // NOI18N
        btnsettings.setText(" Settings");
        btnsettings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsettingsMouseClicked(evt);
            }
        });
        btnsettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsettingsActionPerformed(evt);
            }
        });

        pn_btnminimize.setBackground(new java.awt.Color(10, 104, 71));
        pn_btnminimize.setRoundBottomLeft(25);
        pn_btnminimize.setRoundBottomRight(25);
        pn_btnminimize.setRoundTopLeft(25);
        pn_btnminimize.setRoundTopRight(25);
        pn_btnminimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_btnminimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_btnminimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_btnminimizeMouseExited(evt);
            }
        });

        btnminimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnminimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnminimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnminimizeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_btnminimizeLayout = new javax.swing.GroupLayout(pn_btnminimize);
        pn_btnminimize.setLayout(pn_btnminimizeLayout);
        pn_btnminimizeLayout.setHorizontalGroup(
            pn_btnminimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnminimizeLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnminimize)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        pn_btnminimizeLayout.setVerticalGroup(
            pn_btnminimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnminimizeLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnminimize)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pn_btnmaximize.setBackground(new java.awt.Color(10, 104, 71));
        pn_btnmaximize.setRoundBottomLeft(25);
        pn_btnmaximize.setRoundBottomRight(25);
        pn_btnmaximize.setRoundTopLeft(25);
        pn_btnmaximize.setRoundTopRight(25);
        pn_btnmaximize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_btnmaximizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_btnmaximizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_btnmaximizeMouseExited(evt);
            }
        });

        btnmaximize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnmaximizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnmaximizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnmaximizeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_btnmaximizeLayout = new javax.swing.GroupLayout(pn_btnmaximize);
        pn_btnmaximize.setLayout(pn_btnmaximizeLayout);
        pn_btnmaximizeLayout.setHorizontalGroup(
            pn_btnmaximizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_btnmaximizeLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(btnmaximize)
                .addGap(16, 16, 16))
        );
        pn_btnmaximizeLayout.setVerticalGroup(
            pn_btnmaximizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnmaximizeLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnmaximize)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pn_btnclose.setBackground(new java.awt.Color(10, 104, 71));
        pn_btnclose.setRoundBottomLeft(25);
        pn_btnclose.setRoundBottomRight(25);
        pn_btnclose.setRoundTopLeft(25);
        pn_btnclose.setRoundTopRight(25);
        pn_btnclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_btncloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_btncloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_btncloseMouseExited(evt);
            }
        });

        btnclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncloseMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_btncloseLayout = new javax.swing.GroupLayout(pn_btnclose);
        pn_btnclose.setLayout(pn_btncloseLayout);
        pn_btncloseLayout.setHorizontalGroup(
            pn_btncloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_btncloseLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(btnclose)
                .addGap(16, 16, 16))
        );
        pn_btncloseLayout.setVerticalGroup(
            pn_btncloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_btncloseLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(btnclose)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lbltanggal2)
                .addGap(18, 18, 18)
                .addComponent(lblusername1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblusername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbltanggal1)
                .addGap(18, 18, 18)
                .addComponent(lbltanggal3)
                .addGap(18, 18, 18)
                .addComponent(lbltanggal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 269, Short.MAX_VALUE)
                .addComponent(btnsettings)
                .addGap(34, 34, 34)
                .addComponent(pn_btnminimize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pn_btnmaximize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pn_btnclose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltanggal2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbltanggal1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblusername1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblusername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbltanggal3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbltanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pn_btnclose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pn_btnmaximize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pn_btnminimize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pn_kanan.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        panelCustom1.setBackground(new java.awt.Color(255, 255, 255));
        panelCustom1.setPreferredSize(new java.awt.Dimension(939, 487));
        panelCustom1.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pn_dasarLayout = new javax.swing.GroupLayout(pn_dasar);
        pn_dasar.setLayout(pn_dasarLayout);
        pn_dasarLayout.setHorizontalGroup(
            pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dasarLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(panelCustom1, javax.swing.GroupLayout.DEFAULT_SIZE, 1249, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        pn_dasarLayout.setVerticalGroup(
            pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dasarLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(panelCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, 1003, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        pn_kanan.add(pn_dasar, java.awt.BorderLayout.CENTER);

        getContentPane().add(pn_kanan, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_pembelianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pembelianMouseClicked
        //Mengatur background agar ketika cursor mengarah ke form penjualan, background berubah menjadi warna yg telah ditentukan
        pn_line4.setBackground(new Color(10,124,44));

        panelCustom1.removeAll(); //Menutup form sebelumnya ketika form penjualan di klik
        panelCustom1.add(new pn_pembelian()); //Membuka form penjualan

        //Memperbarui tampilan panel utama setelah form penjualan di buka
        panelCustom1.repaint();
        panelCustom1.revalidate();
    }//GEN-LAST:event_btn_pembelianMouseClicked

    private void btn_pembelianMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pembelianMouseEntered
        pn_line4.setBackground(new Color(10,124,44));
    }//GEN-LAST:event_btn_pembelianMouseEntered

    private void btn_pembelianMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pembelianMouseExited
        pn_line4.setBackground(new Color(10,104,71));
    }//GEN-LAST:event_btn_pembelianMouseExited

    private void btn_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_barangMouseClicked
        pn_line1.setBackground(new Color(10,124,44));

        panelCustom1.removeAll();
        panelCustom1.add(new pn_databarang2()); // digunakan untuk menampilkan menu barang ketika diklik
        panelCustom1.repaint();
        panelCustom1.revalidate();
    }//GEN-LAST:event_btn_barangMouseClicked

    private void btn_barangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_barangMouseEntered
        pn_line1.setBackground(new Color(10,124,44));
    }//GEN-LAST:event_btn_barangMouseEntered

    private void btn_barangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_barangMouseExited
        pn_line1.setBackground(new Color(10,104,71));
    }//GEN-LAST:event_btn_barangMouseExited

    private void btnlappembelianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlappembelianMouseClicked
        pn_line5.setBackground(new Color(10,124,44));

        panelCustom1.removeAll();
        try {
            panelCustom1.add(new pn_lappembelian());
        } catch (SQLException ex) {
            Logger.getLogger(MainMenu2.class.getName()).log(Level.SEVERE, null, ex);
        }
        panelCustom1.repaint();
        panelCustom1.revalidate();
    }//GEN-LAST:event_btnlappembelianMouseClicked

    private void btnlappembelianMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlappembelianMouseEntered
        pn_line5.setBackground(new Color(10,124,44));
    }//GEN-LAST:event_btnlappembelianMouseEntered

    private void btnlappembelianMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlappembelianMouseExited
        pn_line5.setBackground(new Color(10,104,71));
    }//GEN-LAST:event_btnlappembelianMouseExited

    private void btn_dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseClicked
        pn_line.setBackground(new Color(10,124,44));

        panelCustom1.removeAll();
        try {
            panelCustom1.add(new Dashboard2());
        } catch (SQLException ex) {
            Logger.getLogger(MainMenu2.class.getName()).log(Level.SEVERE, null, ex);
        }
        panelCustom1.repaint();
        panelCustom1.revalidate();
    }//GEN-LAST:event_btn_dashboardMouseClicked

    private void btn_dashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseEntered
        pn_line.setBackground(new Color(10,124,44));
    }//GEN-LAST:event_btn_dashboardMouseEntered

    private void btn_dashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseExited
        pn_line.setBackground(new Color(10,104,71));
    }//GEN-LAST:event_btn_dashboardMouseExited

    private void btn_supplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_supplierMouseClicked
        pn_line2.setBackground(new Color(10,124,44));

        panelCustom1.removeAll();
        panelCustom1.add(new pn_datasupplier());
        panelCustom1.repaint();
        panelCustom1.revalidate();
    }//GEN-LAST:event_btn_supplierMouseClicked

    private void btn_supplierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_supplierMouseEntered
        pn_line2.setBackground(new Color(10,124,44));
    }//GEN-LAST:event_btn_supplierMouseEntered

    private void btn_supplierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_supplierMouseExited
        pn_line2.setBackground(new Color(10,104,71));
    }//GEN-LAST:event_btn_supplierMouseExited

    private void btnlappenjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlappenjualanMouseClicked
        // TODO add your handling code here:
        pn_line11.setBackground(new Color(10,124,44));

        panelCustom1.removeAll();
        try {
            panelCustom1.add(new pn_lappenjualan());
        } catch (SQLException ex) {
            Logger.getLogger(MainMenu2.class.getName()).log(Level.SEVERE, null, ex);
        }
        panelCustom1.repaint();
        panelCustom1.revalidate();
    }//GEN-LAST:event_btnlappenjualanMouseClicked

    private void btnlappenjualanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlappenjualanMouseEntered
        // TODO add your handling code here:
        pn_line11.setBackground(new Color(10,124,44));
    }//GEN-LAST:event_btnlappenjualanMouseEntered

    private void btnlappenjualanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlappenjualanMouseExited
        // TODO add your handling code here:
        pn_line11.setBackground(new Color(10,104,71));
    }//GEN-LAST:event_btnlappenjualanMouseExited

    private void btnlapstokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlapstokMouseClicked
        // TODO add your handling code here:
        pn_line6.setBackground(new Color(10,124,44));

        panelCustom1.removeAll();
        panelCustom1.add(new pn_lapstok());
        panelCustom1.repaint();
        panelCustom1.revalidate();
    }//GEN-LAST:event_btnlapstokMouseClicked

    private void btnlapstokMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlapstokMouseEntered
        // TODO add your handling code here:
        pn_line6.setBackground(new Color(10,124,44));
    }//GEN-LAST:event_btnlapstokMouseEntered

    private void btnlapstokMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlapstokMouseExited
        // TODO add your handling code here:
        pn_line6.setBackground(new Color(10,104,71));
    }//GEN-LAST:event_btnlapstokMouseExited

    private void btnpenjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpenjualanMouseClicked
        //Mengatur background agar ketika cursor mengarah ke form penjualan, background berubah menjadi warna yg telah ditentukan
        pn_line9.setBackground(new Color(10,124,44));

        panelCustom1.removeAll(); //Menutup form sebelumnya ketika form penjualan di klik
        panelCustom1.add(new pn_transaksi()); //Membuka form penjualan

        //Memperbarui tampilan panel utama setelah form penjualan di buka
        panelCustom1.repaint();
        panelCustom1.revalidate();
    }//GEN-LAST:event_btnpenjualanMouseClicked

    private void btnpenjualanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpenjualanMouseEntered
        // TODO add your handling code here:
        pn_line9.setBackground(new Color(10,124,44));
    }//GEN-LAST:event_btnpenjualanMouseEntered

    private void btnpenjualanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpenjualanMouseExited
        // TODO add your handling code here:
        pn_line9.setBackground(new Color(10,104,71));
    }//GEN-LAST:event_btnpenjualanMouseExited

    private void btnlapopnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlapopnameMouseClicked
        // TODO add your handling code here:
        pn_line8.setBackground(new Color(10,124,44));

        panelCustom1.removeAll();
        panelCustom1.add(new pn_lapopname());
        panelCustom1.repaint();
        panelCustom1.revalidate();
    }//GEN-LAST:event_btnlapopnameMouseClicked

    private void btnlapopnameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlapopnameMouseEntered
        // TODO add your handling code here:
        pn_line8.setBackground(new Color(10,124,44));
    }//GEN-LAST:event_btnlapopnameMouseEntered

    private void btnlapopnameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlapopnameMouseExited
        // TODO add your handling code here:
        pn_line8.setBackground(new Color(10,104,71));
    }//GEN-LAST:event_btnlapopnameMouseExited

    private void pn_lineMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_lineMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pn_lineMouseEntered

    private void btnmaximizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmaximizeMouseClicked
        // TODO add your handling code here:
        if (this.getExtendedState()!= MainMenu2.MAXIMIZED_BOTH) {
            this.getExtendedState(MainMenu2.MAXIMIZED_BOTH);
        } else {
            this.getExtendedState(MainMenu2.NORMAL);
        }
    }//GEN-LAST:event_btnmaximizeMouseClicked

    private void btnmaximizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmaximizeMouseEntered
        // TODO add your handling code here:
        pn_btnmaximize.setBackground(new Color(10,73,59));
        btnmaximize.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_btnmaximizeMouseEntered

    private void btnmaximizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmaximizeMouseExited
        // TODO add your handling code here:
        pn_btnmaximize.setBackground(new Color(10,104,71));
        btnmaximize.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_btnmaximizeMouseExited

    private void btnminimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnminimizeMouseClicked
        // TODO add your handling code here:
        this.setState(MainMenu2.ICONIFIED);
    }//GEN-LAST:event_btnminimizeMouseClicked

    private void btnminimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnminimizeMouseEntered
        // TODO add your handling code here:
        pn_btnminimize.setBackground(new Color(10,73,59));
        btnminimize.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_btnminimizeMouseEntered

    private void btnminimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnminimizeMouseExited
        // TODO add your handling code here:
        pn_btnminimize.setBackground(new Color(10,104,71));
        btnminimize.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_btnminimizeMouseExited

    private void btncloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btncloseMouseClicked

    private void btncloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseEntered
        // TODO add your handling code here:
        pn_btnclose.setBackground(new Color(255,0,0));
        btnclose.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_btncloseMouseEntered

    private void btncloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseExited
        // TODO add your handling code here:
        pn_btnclose.setBackground(new Color(10,104,71));
        btnclose.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btncloseMouseExited

    private void btnsettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsettingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsettingsActionPerformed

    private void btnsettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsettingsMouseClicked
        // TODO add your handling code here:
        Menu_Settings menu = new Menu_Settings(this, true, this);

        Point p = btnsettings.getLocationOnScreen();
        int x = p.x + btnsettings.getWidth() - menu.getWidth();
        int y = p.y + btnsettings.getHeight();
        menu.setLocation(x, y);
        menu.setVisible(true);
    }//GEN-LAST:event_btnsettingsMouseClicked

    private void pn_btncloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btncloseMouseEntered
        // TODO add your handling code here:
        pn_btnclose.setBackground(new Color(255,0,0));
        btnclose.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_pn_btncloseMouseEntered

    private void pn_btncloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btncloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_pn_btncloseMouseClicked

    private void pn_btncloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btncloseMouseExited
        // TODO add your handling code here:
        pn_btnclose.setBackground(new Color(10,104,71));
        btnclose.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_pn_btncloseMouseExited

    private void pn_btnmaximizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnmaximizeMouseClicked
        // TODO add your handling code here:
        if (this.getExtendedState()!= MainMenu2.MAXIMIZED_BOTH) {
            this.getExtendedState(MainMenu2.MAXIMIZED_BOTH);
        } else {
            this.getExtendedState(MainMenu2.NORMAL);
        }
    }//GEN-LAST:event_pn_btnmaximizeMouseClicked

    private void pn_btnmaximizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnmaximizeMouseEntered
        // TODO add your handling code here:
        pn_btnmaximize.setBackground(new Color(10,73,59));
        btnmaximize.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_pn_btnmaximizeMouseEntered

    private void pn_btnmaximizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnmaximizeMouseExited
        // TODO add your handling code here:
        pn_btnmaximize.setBackground(new Color(10,104,71));
        btnmaximize.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_pn_btnmaximizeMouseExited

    private void pn_btnminimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnminimizeMouseClicked
        // TODO add your handling code here:
        this.setState(MainMenu2.ICONIFIED);
    }//GEN-LAST:event_pn_btnminimizeMouseClicked

    private void pn_btnminimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnminimizeMouseEntered
        // TODO add your handling code here:
        pn_btnminimize.setBackground(new Color(10,73,59));
        btnminimize.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_pn_btnminimizeMouseEntered

    private void pn_btnminimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnminimizeMouseExited
        // TODO add your handling code here:
        pn_btnminimize.setBackground(new Color(10,104,71));
        btnminimize.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_pn_btnminimizeMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Master_Data;
    private javax.swing.JLabel Master_Data2;
    private javax.swing.JLabel Master_Data4;
    private javax.swing.JLabel btn_barang;
    private javax.swing.JLabel btn_dashboard;
    private javax.swing.JLabel btn_pembelian;
    private javax.swing.JLabel btn_supplier;
    private javax.swing.JLabel btnclose;
    private javax.swing.JLabel btnlapopname;
    private javax.swing.JLabel btnlappembelian;
    private javax.swing.JLabel btnlappenjualan;
    private javax.swing.JLabel btnlapstok;
    private javax.swing.JLabel btnmaximize;
    private javax.swing.JLabel btnminimize;
    private javax.swing.JLabel btnpenjualan;
    private javax.swing.JButton btnsettings;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lbltanggal;
    private javax.swing.JLabel lbltanggal1;
    private javax.swing.JLabel lbltanggal2;
    private javax.swing.JLabel lbltanggal3;
    private javax.swing.JLabel lblusername;
    private javax.swing.JLabel lblusername1;
    private javax.swing.JPanel panelCustom1;
    private javax.swing.JPanel pn_btnBarang;
    private javax.swing.JPanel pn_btnBarang1;
    private javax.swing.JPanel pn_btnDashboard;
    private javax.swing.JPanel pn_btnLapPenjualan;
    private javax.swing.JPanel pn_btnLapStok;
    private javax.swing.JPanel pn_btnLaporan;
    private javax.swing.JPanel pn_btnLaporan1;
    private javax.swing.JPanel pn_btnPembelian;
    private javax.swing.JPanel pn_btnSupplier;
    private Custom.PanelCustom pn_btnclose;
    private Custom.PanelCustom pn_btnmaximize;
    private Custom.PanelCustom pn_btnminimize;
    private javax.swing.JPanel pn_dasar;
    private javax.swing.JPanel pn_kanan;
    private javax.swing.JPanel pn_kiri;
    private javax.swing.JPanel pn_line;
    private javax.swing.JPanel pn_line1;
    private javax.swing.JPanel pn_line11;
    private javax.swing.JPanel pn_line2;
    private javax.swing.JPanel pn_line4;
    private javax.swing.JPanel pn_line5;
    private javax.swing.JPanel pn_line6;
    private javax.swing.JPanel pn_line8;
    private javax.swing.JPanel pn_line9;
    // End of variables declaration//GEN-END:variables

    private void getExtendedState(int MAXIMIZED_BOTH) {
        switch (MAXIMIZED_BOTH) {
        case MainMenu2.MAXIMIZED_BOTH:
            this.setExtendedState(JFrame.MAXIMIZED_BOTH);
            break;
        case MainMenu2.NORMAL:
            this.setExtendedState(JFrame.NORMAL);
            break;
        default:
            // Handle invalid state
    }
    }
    
    public JPanel getPanelCustom1(){
        return panelCustom1;
    }
}
