/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package projectkasir;

import java.awt.Color;
import java.awt.Frame;
import javax.swing.JPanel;
/**
 *
 * @author Izzul Islam Ramadhan
 */
public class Menu_Settings extends javax.swing.JDialog {
    
    private MainMenu2 menuUtama;
    /**
     * Creates new form Menu_Settings2
     */
    public Menu_Settings(Frame parent, boolean modal, MainMenu2 menuUtama) {
        super(parent, modal);
        initComponents();
        this.menuUtama = menuUtama;
        setBackground(new Color(0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUtama = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnpassword = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnabout = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnlogout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        panelUtama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelUtamaMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectkasir/padlock.png"))); // NOI18N

        btnpassword.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnpassword.setText("Change Password");
        btnpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnpasswordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnpasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnpasswordMouseExited(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectkasir/information-button.png"))); // NOI18N

        btnabout.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnabout.setText("About");
        btnabout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnaboutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnaboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnaboutMouseExited(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectkasir/logout (1).png"))); // NOI18N

        btnlogout.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnlogout.setText("Logout");
        btnlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnlogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnlogoutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelUtamaLayout = new javax.swing.GroupLayout(panelUtama);
        panelUtama.setLayout(panelUtamaLayout);
        panelUtamaLayout.setHorizontalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUtamaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUtamaLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(25, 25, 25)
                        .addComponent(btnlogout))
                    .addGroup(panelUtamaLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(25, 25, 25)
                        .addComponent(btnabout))
                    .addGroup(panelUtamaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(25, 25, 25)
                        .addComponent(btnpassword)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        panelUtamaLayout.setVerticalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUtamaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnabout, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnpasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpasswordMouseClicked
        // TODO add your handling code here:
        dispose();
        Form_GantiPassword formGanti = new Form_GantiPassword();
        JPanel panelCustom1 = menuUtama.getPanelCustom1();
        panelCustom1.removeAll();
        panelCustom1.add(formGanti);
        panelCustom1.repaint();
        panelCustom1.revalidate();
    }//GEN-LAST:event_btnpasswordMouseClicked

    private void btnpasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpasswordMouseEntered
        // TODO add your handling code here:
        btnpassword.setForeground(new Color(0,51,153));
    }//GEN-LAST:event_btnpasswordMouseEntered

    private void btnpasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpasswordMouseExited
        // TODO add your handling code here:
        btnpassword.setForeground(new Color(38,38,38));
    }//GEN-LAST:event_btnpasswordMouseExited

    private void btnaboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaboutMouseEntered
        // TODO add your handling code here:
        btnabout.setForeground(new Color(0,51,153));
    }//GEN-LAST:event_btnaboutMouseEntered

    private void btnaboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaboutMouseExited
        // TODO add your handling code here:
        btnabout.setForeground(new Color(38,38,38));
    }//GEN-LAST:event_btnaboutMouseExited

    private void btnlogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMouseClicked
        // TODO add your handling code here:
        dispose();
        menuUtama.dispose();
        Login2 lg = new Login2();
        lg.setVisible(true);
    }//GEN-LAST:event_btnlogoutMouseClicked

    private void btnlogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMouseEntered
        // TODO add your handling code here:
        btnlogout.setForeground(new Color(0,51,153));
    }//GEN-LAST:event_btnlogoutMouseEntered

    private void btnlogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMouseExited
        // TODO add your handling code here:
        btnlogout.setForeground(new Color(38,38,38));
    }//GEN-LAST:event_btnlogoutMouseExited

    private void panelUtamaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelUtamaMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_panelUtamaMouseClicked

    private void btnaboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaboutMouseClicked
        // TODO add your handling code here:
        this.dispose();
        MainMenu2 utama = new MainMenu2();
        utama.dispose();
        Form_About ab = new Form_About();
        ab.setVisible(true);
    }//GEN-LAST:event_btnaboutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Menu_Settings dialog = new Menu_Settings(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnabout;
    private javax.swing.JLabel btnlogout;
    private javax.swing.JLabel btnpassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel panelUtama;
    // End of variables declaration//GEN-END:variables
}
