/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectkasir;

import Koneksi.Config;
import java.awt.Color;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author Izzul Islam Ramadhan
 */
public class PasswordBaru extends javax.swing.JFrame {

    /**
     * Creates new form PasswordBaru
     */
    public PasswordBaru() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        txtkonfirmasi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtpassword1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnsubmit = new javax.swing.JButton();
        btnkembali = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btnlogin = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jpanelgradient_11 = new jpanelgradient.jpanelgradient_1();
        jLabel3 = new javax.swing.JLabel();
        pn_btnclose3 = new javax.swing.JPanel();
        btnclose3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 3, 14)); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(769, 527));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Password Baru");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Masukkan password baru");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Konfirmasi");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 130, 60));

        txtusername.setBackground(new java.awt.Color(230, 227, 227));
        txtusername.setFont(new java.awt.Font("Segoe UI Light", 1, 20)); // NOI18N
        txtusername.setForeground(new java.awt.Color(102, 102, 102));
        txtusername.setText("*Masukkan username");
        txtusername.setAutoscrolls(false);
        txtusername.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtusername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtusername.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtusername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtusernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtusernameFocusLost(evt);
            }
        });
        txtusername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtusernameMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtusernameMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtusernameMouseReleased(evt);
            }
        });
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        txtusername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtusernameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtusernameKeyTyped(evt);
            }
        });
        jPanel3.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 330, 40));

        txtkonfirmasi.setBackground(new java.awt.Color(230, 227, 227));
        txtkonfirmasi.setFont(new java.awt.Font("Segoe UI Light", 1, 20)); // NOI18N
        txtkonfirmasi.setForeground(new java.awt.Color(102, 102, 102));
        txtkonfirmasi.setText("*Masukkan password");
        txtkonfirmasi.setAutoscrolls(false);
        txtkonfirmasi.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtkonfirmasi.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtkonfirmasi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtkonfirmasiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtkonfirmasiFocusLost(evt);
            }
        });
        txtkonfirmasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtkonfirmasiMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtkonfirmasiMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtkonfirmasiMouseReleased(evt);
            }
        });
        txtkonfirmasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkonfirmasiActionPerformed(evt);
            }
        });
        txtkonfirmasi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtkonfirmasiKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtkonfirmasiKeyTyped(evt);
            }
        });
        jPanel3.add(txtkonfirmasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 330, 40));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText(":");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 10, 40));

        txtpassword1.setBackground(new java.awt.Color(230, 227, 227));
        txtpassword1.setFont(new java.awt.Font("Segoe UI Light", 1, 20)); // NOI18N
        txtpassword1.setForeground(new java.awt.Color(102, 102, 102));
        txtpassword1.setText("*Masukkan password");
        txtpassword1.setAutoscrolls(false);
        txtpassword1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtpassword1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtpassword1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpassword1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpassword1FocusLost(evt);
            }
        });
        txtpassword1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtpassword1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtpassword1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtpassword1MouseReleased(evt);
            }
        });
        txtpassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpassword1ActionPerformed(evt);
            }
        });
        txtpassword1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpassword1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpassword1KeyTyped(evt);
            }
        });
        jPanel3.add(txtpassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 330, 40));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Password");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 120, 40));

        btnsubmit.setBackground(new java.awt.Color(0, 153, 0));
        btnsubmit.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        btnsubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnsubmit.setText("Submit");
        btnsubmit.setBorder(null);
        btnsubmit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsubmitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsubmitMouseExited(evt);
            }
        });
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });
        jPanel3.add(btnsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 140, 60));

        btnkembali.setBackground(new java.awt.Color(204, 0, 0));
        btnkembali.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        btnkembali.setForeground(new java.awt.Color(255, 255, 255));
        btnkembali.setText("Kembali");
        btnkembali.setBorder(null);
        btnkembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnkembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnkembaliMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnkembaliMouseExited(evt);
            }
        });
        btnkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkembaliActionPerformed(evt);
            }
        });
        jPanel3.add(btnkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 150, 60));

        jLabel11.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        jLabel11.setText("Sudah punya akun ?");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 590, -1, -1));

        btnlogin.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        btnlogin.setForeground(new java.awt.Color(51, 153, 255));
        btnlogin.setText("Login");
        btnlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnloginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnloginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnloginMouseExited(evt);
            }
        });
        jPanel3.add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 590, 50, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Username");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 120, 40));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText(":");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 10, 40));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText(":");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 10, 40));

        jpanelgradient_11.setColorEnd(new java.awt.Color(24, 252, 0));
        jpanelgradient_11.setColorStart(new java.awt.Color(0, 100, 0));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/okok-removebg-preview.png"))); // NOI18N

        pn_btnclose3.setBackground(new java.awt.Color(0, 153, 0));
        pn_btnclose3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_btnclose3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_btnclose3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_btnclose3MouseExited(evt);
            }
        });

        btnclose3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Izzul Islam Ramadhan\\Downloads\\close.png")); // NOI18N
        btnclose3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnclose3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnclose3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnclose3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_btnclose3Layout = new javax.swing.GroupLayout(pn_btnclose3);
        pn_btnclose3.setLayout(pn_btnclose3Layout);
        pn_btnclose3Layout.setHorizontalGroup(
            pn_btnclose3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnclose3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnclose3)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        pn_btnclose3Layout.setVerticalGroup(
            pn_btnclose3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnclose3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnclose3)
                .addGap(10, 10, 10))
        );

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Kasir1-removebg-preview.png"))); // NOI18N

        javax.swing.GroupLayout jpanelgradient_11Layout = new javax.swing.GroupLayout(jpanelgradient_11);
        jpanelgradient_11.setLayout(jpanelgradient_11Layout);
        jpanelgradient_11Layout.setHorizontalGroup(
            jpanelgradient_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelgradient_11Layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(32, 32, 32)
                .addComponent(pn_btnclose3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jpanelgradient_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpanelgradient_11Layout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(12, Short.MAX_VALUE)))
        );
        jpanelgradient_11Layout.setVerticalGroup(
            jpanelgradient_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelgradient_11Layout.createSequentialGroup()
                .addGroup(jpanelgradient_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelgradient_11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pn_btnclose3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelgradient_11Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpanelgradient_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpanelgradient_11Layout.createSequentialGroup()
                    .addGap(137, 137, 137)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(92, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpanelgradient_11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
            .addComponent(jpanelgradient_11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtusernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtusernameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameMouseClicked

    private void txtusernameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtusernameMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameMousePressed

    private void txtusernameMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtusernameMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameMouseReleased

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameActionPerformed

    private void txtusernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusernameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameKeyPressed

    private void txtusernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusernameKeyTyped
        // TODO add your handling code here:
        txtusername.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_txtusernameKeyTyped

    private void txtkonfirmasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtkonfirmasiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkonfirmasiMouseClicked

    private void txtkonfirmasiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtkonfirmasiMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkonfirmasiMousePressed

    private void txtkonfirmasiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtkonfirmasiMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkonfirmasiMouseReleased

    private void txtkonfirmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkonfirmasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkonfirmasiActionPerformed

    private void txtkonfirmasiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtkonfirmasiKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkonfirmasiKeyPressed

    private void txtkonfirmasiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtkonfirmasiKeyTyped
        // TODO add your handling code here:
        txtkonfirmasi.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_txtkonfirmasiKeyTyped

    private void txtpassword1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpassword1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassword1MouseClicked

    private void txtpassword1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpassword1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassword1MousePressed

    private void txtpassword1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpassword1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassword1MouseReleased

    private void txtpassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassword1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassword1ActionPerformed

    private void txtpassword1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpassword1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassword1KeyPressed

    private void txtpassword1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpassword1KeyTyped
        // TODO add your handling code here:
        txtpassword1.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_txtpassword1KeyTyped

    private void btnsubmitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsubmitMouseEntered
        // TODO add your handling code here:
        btnsubmit.setBackground(new Color(0,102,0));
    }//GEN-LAST:event_btnsubmitMouseEntered

    private void btnsubmitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsubmitMouseExited
        // TODO add your handling code here:
        btnsubmit.setBackground(new Color(0,153,0));
    }//GEN-LAST:event_btnsubmitMouseExited

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        // TODO add your handling code here:
        if (txtkonfirmasi.getText().equals("*Masukkan password") || txtpassword1.getText().equals("*Masukkan password") || txtusername.getText().equals("*Masukkan username") ) {
        JOptionPane.showMessageDialog(this, "Silahkan isi data terlebih dahulu !");
        return;
        }
        if (txtusername.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Silahkan isi data terlebih dahulu !");
            return;
        }
    if (txtkonfirmasi.getText().equals(txtkonfirmasi.getText())) {
    try {
        String sqlCheckUsername = "SELECT * FROM akun WHERE username = ?";
        Connection conn = Config.configDB();
        java.sql.PreparedStatement pstCheckUsername = conn.prepareStatement(sqlCheckUsername);
        pstCheckUsername.setString(1, txtusername.getText());
        java.sql.ResultSet rs = pstCheckUsername.executeQuery();
        
        if (!rs.next()) {
            JOptionPane.showMessageDialog(this, "Username tidak ditemukan");
            return;
        }
        
        String sqlUpdatePassword = "UPDATE akun SET password = ? WHERE username = ?";
        java.sql.PreparedStatement pstUpdatePassword = conn.prepareStatement(sqlUpdatePassword);
        pstUpdatePassword.setString(1, txtkonfirmasi.getText());
        pstUpdatePassword.setString(2, txtusername.getText());
        pstUpdatePassword.execute();

        JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
        this.setVisible(false);
        new Login2().setVisible(true);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
} else {
    JOptionPane.showMessageDialog(this, "Konfirmasi password tidak sesuai");
}

    }//GEN-LAST:event_btnsubmitActionPerformed

    private void btnkembaliMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkembaliMouseEntered
        // TODO add your handling code here:
        btnkembali.setBackground(new Color(153,0,0));
    }//GEN-LAST:event_btnkembaliMouseEntered

    private void btnkembaliMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkembaliMouseExited
        // TODO add your handling code here:
        btnkembali.setBackground(new Color(204,0,0));
    }//GEN-LAST:event_btnkembaliMouseExited

    private void btnkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkembaliActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new LupaPassword().setVisible(true);
    }//GEN-LAST:event_btnkembaliActionPerformed

    private void btnloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnloginMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Login2().setVisible(true);
    }//GEN-LAST:event_btnloginMouseClicked

    private void btnloginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnloginMouseEntered
        // TODO add your handling code here:
        btnlogin.setForeground(new Color(0,51,153));
    }//GEN-LAST:event_btnloginMouseEntered

    private void btnloginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnloginMouseExited
        // TODO add your handling code here:
        btnlogin.setForeground(new Color(51,153,255));
    }//GEN-LAST:event_btnloginMouseExited

    private void btnclose3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclose3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnclose3MouseClicked

    private void btnclose3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclose3MouseEntered
        // TODO add your handling code here:
        pn_btnclose3.setBackground(new Color(255,0,0));
        btnclose3.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_btnclose3MouseEntered

    private void btnclose3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclose3MouseExited
        // TODO add your handling code here:
        pn_btnclose3.setBackground(new Color(0,153,0));
        btnclose3.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btnclose3MouseExited

    private void pn_btnclose3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnclose3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_pn_btnclose3MouseClicked

    private void pn_btnclose3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnclose3MouseEntered
        // TODO add your handling code here:
        pn_btnclose3.setBackground(new Color(255,0,0));
        btnclose3.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_pn_btnclose3MouseEntered

    private void pn_btnclose3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnclose3MouseExited
        // TODO add your handling code here:
        pn_btnclose3.setBackground(new Color(0,153,0));
        btnclose3.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_pn_btnclose3MouseExited

    private void txtusernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtusernameFocusGained
        // TODO add your handling code here:
        String user = txtusername.getText();
        if (user.equals("*Masukkan username")) {
            txtusername.setText("");
        }
    }//GEN-LAST:event_txtusernameFocusGained

    private void txtusernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtusernameFocusLost
        // TODO add your handling code here:
        String user = txtusername.getText();
        if (user.equals("") || user.equals("*Masukkan username")) {
            txtusername.setText("*Masukkan username");
            txtusername.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_txtusernameFocusLost

    private void txtpassword1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpassword1FocusGained
        // TODO add your handling code here:
        String user = txtpassword1.getText();
        if (user.equals("*Masukkan password")) {
            txtpassword1.setText("");
        }
    }//GEN-LAST:event_txtpassword1FocusGained

    private void txtpassword1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpassword1FocusLost
        // TODO add your handling code here:
        String user = txtpassword1.getText();
        if (user.equals("") || user.equals("*Masukkan password")) {
            txtpassword1.setText("*Masukkan password");
            txtpassword1.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_txtpassword1FocusLost

    private void txtkonfirmasiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtkonfirmasiFocusGained
        // TODO add your handling code here:
        String user = txtkonfirmasi.getText();
        if (user.equals("*Masukkan password")) {
            txtkonfirmasi.setText("");
        }
    }//GEN-LAST:event_txtkonfirmasiFocusGained

    private void txtkonfirmasiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtkonfirmasiFocusLost
        // TODO add your handling code here:
        String user = txtkonfirmasi.getText();
        if (user.equals("") || user.equals("*Masukkan password")) {
            txtkonfirmasi.setText("*Masukkan password");
            txtkonfirmasi.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_txtkonfirmasiFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PasswordBaru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PasswordBaru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PasswordBaru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PasswordBaru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PasswordBaru().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnclose3;
    private javax.swing.JButton btnkembali;
    private javax.swing.JLabel btnlogin;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private jpanelgradient.jpanelgradient_1 jpanelgradient_11;
    private javax.swing.JPanel pn_btnclose3;
    private javax.swing.JTextField txtkonfirmasi;
    private javax.swing.JTextField txtpassword1;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
