/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectkasir;

import Koneksi.Config;
import java.awt.Color;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author Izzul Islam Ramadhan
 */
public class PasswordToko extends javax.swing.JFrame {

    /**
     * Creates new form LupaPassword
     */
    public PasswordToko() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnlanjut = new javax.swing.JButton();
        btnkembali = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btnlogin = new javax.swing.JLabel();
        txtpassword = new javax.swing.JTextField();
        jpanelgradient_11 = new jpanelgradient.jpanelgradient_1();
        jLabel16 = new javax.swing.JLabel();
        pn_btnclose3 = new javax.swing.JPanel();
        btnclose2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 3, 14)); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(769, 527));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Konfirmasi Register");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Password :");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 120, 40));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Masukkan kata sandi toko");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 300, -1));

        btnlanjut.setBackground(new java.awt.Color(0, 153, 0));
        btnlanjut.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        btnlanjut.setForeground(new java.awt.Color(255, 255, 255));
        btnlanjut.setText("Lanjut");
        btnlanjut.setBorder(null);
        btnlanjut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlanjut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnlanjutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnlanjutMouseExited(evt);
            }
        });
        btnlanjut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlanjutActionPerformed(evt);
            }
        });
        jPanel3.add(btnlanjut, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 140, 60));

        btnkembali.setBackground(new java.awt.Color(204, 0, 0));
        btnkembali.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        btnkembali.setForeground(new java.awt.Color(255, 255, 255));
        btnkembali.setText("Kembali");
        btnkembali.setBorder(null);
        btnkembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnkembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnkembaliMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnkembaliMouseExited(evt);
            }
        });
        btnkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkembaliActionPerformed(evt);
            }
        });
        jPanel3.add(btnkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 150, 60));

        jLabel11.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        jLabel11.setText("Sudah punya akun ?");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 580, 180, -1));

        btnlogin.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        btnlogin.setForeground(new java.awt.Color(51, 153, 255));
        btnlogin.setText("Login");
        btnlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnloginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnloginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnloginMouseExited(evt);
            }
        });
        jPanel3.add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 580, 50, -1));

        txtpassword.setBackground(new java.awt.Color(230, 227, 227));
        txtpassword.setFont(new java.awt.Font("Segoe UI Light", 1, 20)); // NOI18N
        txtpassword.setForeground(new java.awt.Color(102, 102, 102));
        txtpassword.setText("*Masukkan password");
        txtpassword.setAutoscrolls(false);
        txtpassword.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtpassword.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpasswordFocusLost(evt);
            }
        });
        txtpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtpasswordMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtpasswordMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtpasswordMouseReleased(evt);
            }
        });
        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });
        txtpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpasswordKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpasswordKeyTyped(evt);
            }
        });
        jPanel3.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 330, 40));

        jpanelgradient_11.setColorEnd(new java.awt.Color(24, 252, 0));
        jpanelgradient_11.setColorStart(new java.awt.Color(0, 100, 0));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/konfirmasi.png"))); // NOI18N

        pn_btnclose3.setBackground(new java.awt.Color(0, 153, 0));
        pn_btnclose3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_btnclose3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_btnclose3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_btnclose3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pn_btnclose3MousePressed(evt);
            }
        });

        btnclose2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Izzul Islam Ramadhan\\Downloads\\close.png")); // NOI18N
        btnclose2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnclose2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnclose2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnclose2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_btnclose3Layout = new javax.swing.GroupLayout(pn_btnclose3);
        pn_btnclose3.setLayout(pn_btnclose3Layout);
        pn_btnclose3Layout.setHorizontalGroup(
            pn_btnclose3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnclose3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnclose2)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        pn_btnclose3Layout.setVerticalGroup(
            pn_btnclose3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnclose3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnclose2)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout jpanelgradient_11Layout = new javax.swing.GroupLayout(jpanelgradient_11);
        jpanelgradient_11.setLayout(jpanelgradient_11Layout);
        jpanelgradient_11Layout.setHorizontalGroup(
            jpanelgradient_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelgradient_11Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelgradient_11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pn_btnclose3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpanelgradient_11Layout.setVerticalGroup(
            jpanelgradient_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelgradient_11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_btnclose3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpanelgradient_11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
            .addComponent(jpanelgradient_11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnlanjutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlanjutMouseEntered
        // TODO add your handling code here:
        btnlanjut.setBackground(new Color(0,102,0));
    }//GEN-LAST:event_btnlanjutMouseEntered

    private void btnlanjutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlanjutMouseExited
        // TODO add your handling code here:
        btnlanjut.setBackground(new Color(0,153,0));
    }//GEN-LAST:event_btnlanjutMouseExited

    private void btnlanjutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlanjutActionPerformed
        // TODO add your handling code here:
        String password = txtpassword.getText();

        if (password.equals("112233")) {
            this.setVisible(false);
            new Register2().setVisible(true);
        } else {
        JOptionPane.showMessageDialog(null, "PASSWORD SALAH");
    }
    }//GEN-LAST:event_btnlanjutActionPerformed

    private void btnkembaliMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkembaliMouseEntered
        // TODO add your handling code here:
        btnkembali.setBackground(new Color(153,0,0));
    }//GEN-LAST:event_btnkembaliMouseEntered

    private void btnkembaliMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkembaliMouseExited
        // TODO add your handling code here:
        btnkembali.setBackground(new Color(204,0,0));
    }//GEN-LAST:event_btnkembaliMouseExited

    private void btnkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkembaliActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Login2().setVisible(true);
    }//GEN-LAST:event_btnkembaliActionPerformed

    private void btnloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnloginMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Login2().setVisible(true);
    }//GEN-LAST:event_btnloginMouseClicked

    private void btnloginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnloginMouseEntered
        // TODO add your handling code here:
        btnlogin.setForeground(new Color(0,51,153));
    }//GEN-LAST:event_btnloginMouseEntered

    private void btnloginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnloginMouseExited
        // TODO add your handling code here:
        btnlogin.setForeground(new Color(51,153,255));
    }//GEN-LAST:event_btnloginMouseExited

    private void btnclose2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclose2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnclose2MouseClicked

    private void btnclose2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclose2MouseEntered
        // TODO add your handling code here:
        pn_btnclose3.setBackground(new Color(255,0,0));
        btnclose2.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_btnclose2MouseEntered

    private void btnclose2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclose2MouseExited
        // TODO add your handling code here:
        pn_btnclose3.setBackground(new Color(0,153,0));
        btnclose2.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btnclose2MouseExited

    private void pn_btnclose3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnclose3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_pn_btnclose3MouseClicked

    private void pn_btnclose3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnclose3MouseEntered
        // TODO add your handling code here:
        pn_btnclose3.setBackground(new Color(255,0,0));
        btnclose2.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_pn_btnclose3MouseEntered

    private void pn_btnclose3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnclose3MouseExited
        // TODO add your handling code here:
        pn_btnclose3.setBackground(new Color(0,153,0));
        btnclose2.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_pn_btnclose3MouseExited

    private void pn_btnclose3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnclose3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_pn_btnclose3MousePressed

    private void txtpasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpasswordFocusGained
        // TODO add your handling code here:
        String user = txtpassword.getText();
        if (user.equals("*Masukkan password")) {
            txtpassword.setText("");
        }
    }//GEN-LAST:event_txtpasswordFocusGained

    private void txtpasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpasswordFocusLost
        // TODO add your handling code here:
        String user = txtpassword.getText();
        if (user.equals("") || user.equals("*Masukkan password")) {
            txtpassword.setText("*Masukkan password");
            txtpassword.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_txtpasswordFocusLost

    private void txtpasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpasswordMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordMouseClicked

    private void txtpasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpasswordMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordMousePressed

    private void txtpasswordMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpasswordMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordMouseReleased

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordActionPerformed

    private void txtpasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasswordKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordKeyPressed

    private void txtpasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasswordKeyTyped
        // TODO add your handling code here:
        txtpassword.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_txtpasswordKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PasswordToko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PasswordToko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PasswordToko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PasswordToko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PasswordToko().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnclose2;
    private javax.swing.JButton btnkembali;
    private javax.swing.JButton btnlanjut;
    private javax.swing.JLabel btnlogin;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private jpanelgradient.jpanelgradient_1 jpanelgradient_11;
    private javax.swing.JPanel pn_btnclose3;
    private javax.swing.JTextField txtpassword;
    // End of variables declaration//GEN-END:variables
}
