/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package projectkasir;

import Koneksi.Config;
import java.awt.Color;
import java.awt.Font;
import java.awt.Label;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;


/**
 *
 * @author Izzul Islam Ramadhan
 */
public class pn_lappembelian extends javax.swing.JPanel {
    
    private final Connection conn; 
    private final int noColumnIndex = 0;
    private final int noColumnWidth = 50;
    
    /**
     * Creates new form pn_lappembelian
     */
    public pn_lappembelian() throws SQLException {
        initComponents();
        conn= Config.configDB();
        txtpencarian.setText("");
        txtpencarian2.setText("");
        
        load_table();
        setBackground(new Color(255,255,255));
        
        tbllappembelian.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 18));
        tbllappembelian.getTableHeader().setOpaque(false);
        tbllappembelian.setBackground(new Color(122,186,120));
        tbllappembelian.setForeground(new Color(255,255,255));
        tbllappembelian.setRowHeight(35);
        txtpencarian.setText(null);
        setColumnWidth();
        
        String total = jml_pengeluaran(txtpencarian.getText());
        lbl_totalP.setText(total);
    }
    
    
    private void load_table(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No.");
        model.addColumn("No. Pembelian");
        model.addColumn("Kode Supplier");
        model.addColumn("Nama Supplier");
        model.addColumn("Kode Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Harga Barang");
        model.addColumn("Jumlah");
        model.addColumn("Subtotal");
        model.addColumn("Tanggal");
        
        String cari = txtpencarian.getText();
        String cari2 = txtpencarian2.getText();
        try {
            int no=1;
            String query = "SELECT pembelian.id_pembelian, detail_pembelian.id_supplier, detail_pembelian.nama_supplier, detail_pembelian.id_barang, detail_pembelian.nama_barang, detail_pembelian.harga_barang, detail_pembelian.jumlah_barang, detail_pembelian.subtotal, pembelian.tgl_pembelian " +
                "FROM pembelian INNER JOIN detail_pembelian ON pembelian.id_pembelian = detail_pembelian.id_pembelian " + "WHERE pembelian.tgl_pembelian LIKE '%" + cari + "%'" + " OR pembelian.tgl_pembelian BETWEEN '" + cari + "' AND '" + cari2 + "'";
            Connection conn= Config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(query);
            while(res.next()) {
                model.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7),res.getString(8),res.getString(9)});
            }
            tbllappembelian.setModel(model);
            tbllappembelian.disable();
        } catch (Exception e) {
            System.out.print(e.getMessage());
        }
        setColumnWidth();
    }
    
    private void setColumnWidth() {
        TableColumnModel columnModel = tbllappembelian.getColumnModel();
        columnModel.getColumn(noColumnIndex).setPreferredWidth(noColumnWidth);
        columnModel.getColumn(noColumnIndex).setMaxWidth(noColumnWidth);
        columnModel.getColumn(noColumnIndex).setMinWidth(noColumnWidth);
        tbllappembelian.getColumnModel().getColumn(5).setPreferredWidth(250);
        tbllappembelian.getColumnModel().getColumn(5).setMaxWidth(250);
        tbllappembelian.getColumnModel().getColumn(5).setMinWidth(250);
        tbllappembelian.getColumnModel().getColumn(3).setPreferredWidth(200);
        tbllappembelian.getColumnModel().getColumn(3).setMaxWidth(200);
        tbllappembelian.getColumnModel().getColumn(3).setMinWidth(200);
    }
    
    private void Bersih(){
        txtpencarian.setText("");
        txtpencarian2.setText("");
        load_table();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cari_tanggal = new com.raven.datechooser.DateChooser();
        cari_tanggal2 = new com.raven.datechooser.DateChooser();
        btncari = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtpencarian = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbllappembelian = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl_totalP = new javax.swing.JLabel();
        btnrefresh = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtpencarian2 = new javax.swing.JTextField();

        cari_tanggal.setForeground(new java.awt.Color(29, 0, 174));
        cari_tanggal.setDateFormat("yyyy-MM-dd");
        cari_tanggal.setFocusable(false);
        cari_tanggal.setTextRefernce(txtpencarian);

        cari_tanggal2.setForeground(new java.awt.Color(29, 0, 174));
        cari_tanggal2.setDateFormat("yyyy-MM-dd");
        cari_tanggal2.setFocusable(false);
        cari_tanggal2.setTextRefernce(txtpencarian2);

        setBackground(new java.awt.Color(255, 255, 255));

        btncari.setBackground(new java.awt.Color(10, 104, 71));
        btncari.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btncari.setForeground(new java.awt.Color(255, 255, 255));
        btncari.setText("Cari");
        btncari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncariMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncariMouseExited(evt);
            }
        });
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel4.setText("Tampilkan data Dari Tanggal :");

        txtpencarian.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtpencarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpencarianActionPerformed(evt);
            }
        });
        txtpencarian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpencarianKeyPressed(evt);
            }
        });

        tbllappembelian.setBackground(new java.awt.Color(180, 230, 253));
        tbllappembelian.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tbllappembelian.setForeground(new java.awt.Color(0, 0, 0));
        tbllappembelian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No.", "No. Pembelian", "Kode Supplier", "Supplier", "Kode Barang", "Nama Barang", "Harga Barang", "Jumlah", "Subtotal", "Tanggal"
            }
        ));
        tbllappembelian.setFocusable(false);
        tbllappembelian.setGridColor(new java.awt.Color(0, 0, 0));
        tbllappembelian.setRowHeight(25);
        tbllappembelian.setSelectionBackground(new java.awt.Color(255, 0, 51));
        tbllappembelian.setShowHorizontalLines(true);
        tbllappembelian.getTableHeader().setReorderingAllowed(false);
        tbllappembelian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbllappembelianMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbllappembelian);
        if (tbllappembelian.getColumnModel().getColumnCount() > 0) {
            tbllappembelian.getColumnModel().getColumn(0).setPreferredWidth(35);
        }

        jPanel3.setBackground(new java.awt.Color(10, 104, 71));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setFont(new java.awt.Font("Bookman Old Style", 1, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Riwayat Pembelian");

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Laporan > Pembelian");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 22)); // NOI18N
        jLabel1.setText("Total Pembelian :");

        jPanel1.setBackground(new java.awt.Color(122, 186, 120));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        lbl_totalP.setBackground(new java.awt.Color(122, 186, 120));
        lbl_totalP.setFont(new java.awt.Font("Segoe UI Black", 0, 22)); // NOI18N
        lbl_totalP.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(lbl_totalP, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_totalP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnrefresh.setBackground(new java.awt.Color(10, 104, 71));
        btnrefresh.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnrefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnrefresh.setText("Refresh");
        btnrefresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnrefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnrefreshMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnrefreshMouseExited(evt);
            }
        });
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel5.setText("Sampai Tanggal");

        txtpencarian2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtpencarian2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpencarian2ActionPerformed(evt);
            }
        });
        txtpencarian2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpencarian2KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtpencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtpencarian2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btncari)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnrefresh)
                .addGap(143, 143, 143))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btncari)
                    .addComponent(txtpencarian)
                    .addComponent(btnrefresh)
                    .addComponent(jLabel5)
                    .addComponent(txtpencarian2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addGap(60, 60, 60))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        // TODO add your handling code here:
        if (txtpencarian.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Silahkan isi data terlebih dahulu !");
            return;
        }
        load_table();
        String total = null;
        try {
            total = jml_pengeluaran(txtpencarian.getText());
        } catch (SQLException ex) {
            Logger.getLogger(pn_lappembelian.class.getName()).log(Level.SEVERE, null, ex);
        }
        lbl_totalP.setText(total);
        setColumnWidth();
    }//GEN-LAST:event_btncariActionPerformed

    private void tbllappembelianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbllappembelianMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbllappembelianMouseClicked

    private void txtpencarianKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpencarianKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpencarianKeyPressed

    private void txtpencarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpencarianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpencarianActionPerformed

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
        Bersih();
        String total = null;
        try { //digunakan untuk melakukan penyesuaian terhadap total pengeluaran ketika tombol refresh diklik 
            total = jml_pengeluaran(txtpencarian.getText());
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard2.class.getName()).log(Level.SEVERE, null, ex);
        }
        lbl_totalP.setText(total);
    }//GEN-LAST:event_btnrefreshActionPerformed

    private void btncariMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncariMouseEntered
        // TODO add your handling code here:
        btncari.setBackground(new Color(0,89,8));
    }//GEN-LAST:event_btncariMouseEntered

    private void btncariMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncariMouseExited
        // TODO add your handling code here:
        btncari.setBackground(new Color(10,104,71));
    }//GEN-LAST:event_btncariMouseExited

    private void btnrefreshMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnrefreshMouseEntered
        // TODO add your handling code here:
        btnrefresh.setBackground(new Color(0,89,8));
    }//GEN-LAST:event_btnrefreshMouseEntered

    private void btnrefreshMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnrefreshMouseExited
        // TODO add your handling code here:
        btnrefresh.setBackground(new Color(10,104,71));
    }//GEN-LAST:event_btnrefreshMouseExited

    private void txtpencarian2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpencarian2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpencarian2ActionPerformed

    private void txtpencarian2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpencarian2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpencarian2KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncari;
    private javax.swing.JButton btnrefresh;
    private com.raven.datechooser.DateChooser cari_tanggal;
    private com.raven.datechooser.DateChooser cari_tanggal2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_totalP;
    private javax.swing.JTable tbllappembelian;
    private javax.swing.JTextField txtpencarian;
    private javax.swing.JTextField txtpencarian2;
    // End of variables declaration//GEN-END:variables
        
        private String jml_pengeluaran(String text)throws SQLException {
            String cari = txtpencarian.getText();
            String cari2 = txtpencarian2.getText();
            String sql = "SELECT SUM(pembelian.total) AS total FROM pembelian WHERE pembelian.tgl_pembelian LIKE '%" + cari + "%'" + " OR pembelian.tgl_pembelian BETWEEN '" + cari + "' AND '" + cari2 + "'";
            java.sql.Statement stm = conn.createStatement();
            ResultSet res = stm.executeQuery(sql);
            
            res.next();
            int jumlah = res.getInt("total");
            
            Label lbl_totalP = new Label("total pengeluaran: ");
            String data_jumlah = formatRupiah(jumlah);

            return data_jumlah;
        }
        private String formatRupiah(int amount) {
        // Membuat objek NumberFormat dengan format mata uang Rupiah
        NumberFormat rupiahFormat = new DecimalFormat("#,###,###,###");

        // Menggunakan metode format untuk mengonversi nilai ke format Rupiah
        return "Rp " + rupiahFormat.format(amount);
        }
}