/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package projectkasir;

import Koneksi.Config;
import java.awt.Color;
import java.awt.Font;
import java.awt.Label;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Izzul Islam Ramadhan
 */
public class pn_lappenjualan extends javax.swing.JPanel {
    
    private final Connection conn; 
    private final int noColumnIndex = 0;
    private final int noColumnWidth = 50;
    /**
     * Creates new form pn_lappenjualan
     */
    public pn_lappenjualan() throws SQLException {
        initComponents();
        conn= Config.configDB();
        txtpencarian.setText("");
        txtpencarian2.setText("");
        
        load_table();
        
        setBackground(new Color(255,255,255));
        
        tbllappenjualan.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 18));
        tbllappenjualan.getTableHeader().setOpaque(false);
        tbllappenjualan.setBackground(new Color(122,186,120));
        tbllappenjualan.setForeground(new Color(255,255,255));
        tbllappenjualan.setRowHeight(35);
        txtpencarian.setText(null);
        setColumnWidth();
        
        String total = jml_pembelian2(txtpencarian.getText());
        String untung = jml_untung(txtpencarian.getText());
        lbl_totalP.setText(total);
        lbl_untung.setText(untung);
    }
    
    private void load_table(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No.");
        model.addColumn("No.Transaksi");
        model.addColumn("Kode Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Harga Barang");
        model.addColumn("Jumlah");
        model.addColumn("Subtotal");
        model.addColumn("Tanggal");
        
        String cari = txtpencarian.getText();
        String cari2 = txtpencarian2.getText();
        try {
            int no=1;
            String query = "SELECT transaksi.id_transaksi, detail_transaksi.id_barang, detail_transaksi.nama_barang, detail_transaksi.harga_barang, detail_transaksi.jumlah_barang, detail_transaksi.subtotal, transaksi.tgl_transaksi " +
            "FROM transaksi INNER JOIN detail_transaksi ON transaksi.id_transaksi = detail_transaksi.id_transaksi " +
            "WHERE transaksi.tgl_transaksi LIKE '%" + cari + "%'" + " OR transaksi.tgl_transaksi BETWEEN '" + cari + "' AND '" + cari2 + "'";
            Connection conn= Config.configDB();
            java.sql.Statement stm=conn.createStatement();
            ResultSet res=stm.executeQuery(query);
            while(res.next()) {
                model.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7)});
            }
            tbllappenjualan.setModel(model);
            tbllappenjualan.disable();
        } catch (Exception e) {
            System.out.print(e.getMessage());
        }
        setColumnWidth();
    }
    
    private void setColumnWidth() {
        TableColumnModel columnModel = tbllappenjualan.getColumnModel();
        columnModel.getColumn(noColumnIndex).setPreferredWidth(noColumnWidth);
        columnModel.getColumn(noColumnIndex).setMaxWidth(noColumnWidth);
        columnModel.getColumn(noColumnIndex).setMinWidth(noColumnWidth);
        tbllappenjualan.getColumnModel().getColumn(3).setPreferredWidth(250);
        tbllappenjualan.getColumnModel().getColumn(3).setMaxWidth(250);
        tbllappenjualan.getColumnModel().getColumn(3).setMinWidth(250);
        tbllappenjualan.getColumnModel().getColumn(2).setPreferredWidth(150);
        tbllappenjualan.getColumnModel().getColumn(2).setMaxWidth(150);
        tbllappenjualan.getColumnModel().getColumn(2).setMinWidth(150);
    }
    
    private void Bersih(){
        txtpencarian.setText("");
        txtpencarian2.setText("");
        load_table();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cari_tanggal = new com.raven.datechooser.DateChooser();
        cari_tanggal2 = new com.raven.datechooser.DateChooser();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbllappenjualan = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lbl_totalP = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnrefresh = new javax.swing.JButton();
        btncari = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtpencarian = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtpencarian2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lbl_untung = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        cari_tanggal.setForeground(new java.awt.Color(29, 0, 174));
        cari_tanggal.setDateFormat("yyyy-MM-dd");
        cari_tanggal.setFocusable(false);
        cari_tanggal.setTextRefernce(txtpencarian);

        cari_tanggal2.setForeground(new java.awt.Color(29, 0, 174));
        cari_tanggal2.setDateFormat("yyyy-MM-dd");
        cari_tanggal2.setFocusable(false);
        cari_tanggal2.setTextRefernce(txtpencarian2);

        jPanel3.setBackground(new java.awt.Color(10, 104, 71));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setFont(new java.awt.Font("Bookman Old Style", 1, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Riwayat Penjualan");

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Laporan > Penjualan");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 641, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        tbllappenjualan.setBackground(new java.awt.Color(180, 230, 253));
        tbllappenjualan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tbllappenjualan.setForeground(new java.awt.Color(0, 0, 0));
        tbllappenjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No.", "No. Transaksi", "Kode Barang", "Nama Barang", "Harga Barang", "Jumlah", "Subtotal", "Tanggal"
            }
        ));
        tbllappenjualan.setFocusable(false);
        tbllappenjualan.setGridColor(new java.awt.Color(0, 0, 0));
        tbllappenjualan.setRowHeight(25);
        tbllappenjualan.setSelectionBackground(new java.awt.Color(0, 51, 204));
        tbllappenjualan.setShowHorizontalLines(true);
        tbllappenjualan.getTableHeader().setReorderingAllowed(false);
        tbllappenjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbllappenjualanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbllappenjualan);

        jPanel1.setBackground(new java.awt.Color(122, 186, 120));

        lbl_totalP.setBackground(new java.awt.Color(153, 255, 255));
        lbl_totalP.setFont(new java.awt.Font("Segoe UI Black", 0, 22)); // NOI18N
        lbl_totalP.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(lbl_totalP, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_totalP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 22)); // NOI18N
        jLabel1.setText("Total Penjualan :");

        btnrefresh.setBackground(new java.awt.Color(10, 104, 71));
        btnrefresh.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnrefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnrefresh.setText("Refresh");
        btnrefresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnrefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnrefreshMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnrefreshMouseExited(evt);
            }
        });
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });

        btncari.setBackground(new java.awt.Color(10, 104, 71));
        btncari.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btncari.setForeground(new java.awt.Color(255, 255, 255));
        btncari.setText("Cari");
        btncari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncariMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncariMouseExited(evt);
            }
        });
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel4.setText("Tampilkan data Dari Tanggal :");

        txtpencarian.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtpencarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpencarianActionPerformed(evt);
            }
        });
        txtpencarian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpencarianKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel5.setText("Sampai Tanggal");

        txtpencarian2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtpencarian2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpencarian2ActionPerformed(evt);
            }
        });
        txtpencarian2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpencarian2KeyPressed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(122, 186, 120));

        lbl_untung.setBackground(new java.awt.Color(153, 255, 255));
        lbl_untung.setFont(new java.awt.Font("Segoe UI Black", 0, 22)); // NOI18N
        lbl_untung.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(lbl_untung, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_untung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 22)); // NOI18N
        jLabel2.setText("Total Keuntungan :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtpencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtpencarian2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btncari)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnrefresh)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btncari)
                    .addComponent(txtpencarian)
                    .addComponent(btnrefresh)
                    .addComponent(jLabel5)
                    .addComponent(txtpencarian2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbllappenjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbllappenjualanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbllappenjualanMouseClicked

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
        Bersih();
        String total = null;
        try {
            total = jml_pembelian2(txtpencarian.getText());
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard2.class.getName()).log(Level.SEVERE, null, ex);
        }
        lbl_totalP.setText(total);
    }//GEN-LAST:event_btnrefreshActionPerformed

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        // TODO add your handling code here:
        if (txtpencarian.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Silahkan isi data terlebih dahulu !");
            return;
        }
        load_table();
        String total = null;
        String untung = null;
        try { 
            total = jml_pembelian2(txtpencarian.getText());
            untung = jml_untung(txtpencarian.getText());
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard2.class.getName()).log(Level.SEVERE, null, ex);
        }
        lbl_totalP.setText(total);
        lbl_untung.setText(untung);
        setColumnWidth();
    }//GEN-LAST:event_btncariActionPerformed

    private void txtpencarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpencarianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpencarianActionPerformed

    private void txtpencarianKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpencarianKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpencarianKeyPressed

    private void btncariMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncariMouseEntered
        // TODO add your handling code here:
        btncari.setBackground(new Color(0,89,8));
    }//GEN-LAST:event_btncariMouseEntered

    private void btncariMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncariMouseExited
        // TODO add your handling code here:
        btncari.setBackground(new Color(10,104,71));
    }//GEN-LAST:event_btncariMouseExited

    private void btnrefreshMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnrefreshMouseEntered
        // TODO add your handling code here:
        btnrefresh.setBackground(new Color(0,89,8));
    }//GEN-LAST:event_btnrefreshMouseEntered

    private void btnrefreshMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnrefreshMouseExited
        // TODO add your handling code here:
        btnrefresh.setBackground(new Color(10,104,71));
    }//GEN-LAST:event_btnrefreshMouseExited

    private void txtpencarian2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpencarian2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpencarian2ActionPerformed

    private void txtpencarian2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpencarian2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpencarian2KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncari;
    private javax.swing.JButton btnrefresh;
    private com.raven.datechooser.DateChooser cari_tanggal;
    private com.raven.datechooser.DateChooser cari_tanggal2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_totalP;
    private javax.swing.JLabel lbl_untung;
    private javax.swing.JTable tbllappenjualan;
    private javax.swing.JTextField txtpencarian;
    private javax.swing.JTextField txtpencarian2;
    // End of variables declaration//GEN-END:variables
    private String jml_pembelian2(String text)throws SQLException {
            String cari = txtpencarian.getText(); //Mengambil teks kriteria tanggal transaksi dari komponen txtpencarian
            String cari2 = txtpencarian2.getText();
            String sql = "SELECT SUM(transaksi.total) AS total FROM transaksi WHERE transaksi.tgl_transaksi LIKE '%" + cari + "%'" + " OR transaksi.tgl_transaksi BETWEEN '" + cari + "' AND '" + cari2 + "'"; //Membuat kueri SQL untuk menghitung total jumlah pembelian berdasarkan kriteria tanggal transaksi.
            java.sql.Statement stm = conn.createStatement(); //Melakukan eksekusi kueri SQL menggunakan objek Statement.
            ResultSet res = stm.executeQuery(sql); //Membaca hasil kueri SQL menggunakan objek ResultSet.
            
            res.next(); 
            int jumlah = res.getInt("total"); //Mengambil nilai total jumlah pembelian dari hasil kueri SQL
            
            Label lbl_totalP = new Label("total pemasukan: ");
            String data_jumlah = formatRupiah(jumlah); //Mengkonversi nilai total jumlah pembelian ke dalam bentuk String.

            return data_jumlah; //Mengembalikan nilai total jumlah pembelian dalam bentuk String.
        }
    
    private String jml_untung(String text) throws SQLException {
        
        String sql = "SELECT SUM(total_keuntungan) AS total_keuntungan_keseluruhan FROM view_keuntungan_transaksi WHERE view_keuntungan_transaksi.tgl_transaksi LIKE '%" + txtpencarian.getText() + "%'" + " OR view_keuntungan_transaksi.tgl_transaksi BETWEEN '" + txtpencarian.getText() + "' AND '" + txtpencarian2.getText() + "'";
        java.sql.Statement stm = conn.createStatement();
        ResultSet res = stm.executeQuery(sql);
        
        res.next();
        int jumlah = res.getInt("total_keuntungan_keseluruhan");
        
        String data_jumlah = formatRupiah(jumlah);
        return data_jumlah;
    }
    
    private String formatRupiah(int amount) {
        // Membuat objek NumberFormat dengan format mata uang Rupiah
        NumberFormat rupiahFormat = new DecimalFormat("#,###,###,###");

        // Menggunakan metode format untuk mengonversi nilai ke format Rupiah
        return "Rp " + rupiahFormat.format(amount);
        }
}
