/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectkasir;
import Koneksi.Config;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author Izzul Islam Ramadhan
 */
public class Register2 extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnlogin = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnsubmit = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        txtpassword = new javax.swing.JTextField();
        txtusername = new javax.swing.JTextField();
        txttelepon = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        jpanelgradient_11 = new jpanelgradient.jpanelgradient_1();
        jLabel3 = new javax.swing.JLabel();
        pn_btnclose3 = new javax.swing.JPanel();
        btnclose3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        jLabel12.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel12.setText("Sudah punya akun ?");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(769, 527));

        jLabel11.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        jLabel11.setText("Sudah punya akun ?");

        btnlogin.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        btnlogin.setForeground(new java.awt.Color(51, 153, 255));
        btnlogin.setText("Login");
        btnlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnloginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnloginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnloginMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Halo, Kasir!");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Silahkan isi data dibawah ini ");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("untuk membuat akun");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Nama");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("No. Handphone");

        jLabel14.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Username");

        jLabel15.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Password");

        btnsubmit.setBackground(new java.awt.Color(0, 153, 0));
        btnsubmit.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        btnsubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnsubmit.setText("Submit");
        btnsubmit.setBorder(null);
        btnsubmit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsubmitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsubmitMouseExited(evt);
            }
        });
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });

        btncancel.setBackground(new java.awt.Color(204, 0, 0));
        btncancel.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        btncancel.setForeground(new java.awt.Color(255, 255, 255));
        btncancel.setText("Cancel");
        btncancel.setBorder(null);
        btncancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncancelMouseExited(evt);
            }
        });
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        txtpassword.setBackground(new java.awt.Color(230, 227, 227));
        txtpassword.setFont(new java.awt.Font("Segoe UI Light", 1, 20)); // NOI18N
        txtpassword.setForeground(new java.awt.Color(102, 102, 102));
        txtpassword.setText("*Masukkan password");
        txtpassword.setAutoscrolls(false);
        txtpassword.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtpassword.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpasswordFocusLost(evt);
            }
        });
        txtpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtpasswordMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtpasswordMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtpasswordMouseReleased(evt);
            }
        });
        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });
        txtpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpasswordKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpasswordKeyTyped(evt);
            }
        });

        txtusername.setBackground(new java.awt.Color(230, 227, 227));
        txtusername.setFont(new java.awt.Font("Segoe UI Light", 1, 20)); // NOI18N
        txtusername.setForeground(new java.awt.Color(102, 102, 102));
        txtusername.setText("*Masukkan username");
        txtusername.setAutoscrolls(false);
        txtusername.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtusername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtusername.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtusername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtusernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtusernameFocusLost(evt);
            }
        });
        txtusername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtusernameMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtusernameMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtusernameMouseReleased(evt);
            }
        });
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        txtusername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtusernameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtusernameKeyTyped(evt);
            }
        });

        txttelepon.setBackground(new java.awt.Color(230, 227, 227));
        txttelepon.setFont(new java.awt.Font("Segoe UI Light", 1, 20)); // NOI18N
        txttelepon.setForeground(new java.awt.Color(102, 102, 102));
        txttelepon.setText("*Masukkan nomor handphone");
        txttelepon.setAutoscrolls(false);
        txttelepon.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txttelepon.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txttelepon.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txttelepon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtteleponFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtteleponFocusLost(evt);
            }
        });
        txttelepon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtteleponMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtteleponMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtteleponMouseReleased(evt);
            }
        });
        txttelepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtteleponActionPerformed(evt);
            }
        });
        txttelepon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtteleponKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtteleponKeyTyped(evt);
            }
        });

        txtnama.setBackground(new java.awt.Color(230, 227, 227));
        txtnama.setFont(new java.awt.Font("Segoe UI Light", 1, 20)); // NOI18N
        txtnama.setForeground(new java.awt.Color(102, 102, 102));
        txtnama.setText("*Masukkan nama lengkap");
        txtnama.setAutoscrolls(false);
        txtnama.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtnama.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtnama.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtnama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnamaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnamaFocusLost(evt);
            }
        });
        txtnama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtnamaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtnamaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtnamaMouseReleased(evt);
            }
        });
        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });
        txtnama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnamaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnamaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 76, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addComponent(jLabel6))
                        .addComponent(jLabel10)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(jLabel13)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btncancel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(btnsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)
                        .addComponent(jLabel14)
                        .addComponent(jLabel15)
                        .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txttelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(99, 99, 99))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnlogin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGap(25, 25, 25)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txttelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncancel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(btnlogin))
                .addContainerGap())
        );

        jpanelgradient_11.setColorEnd(new java.awt.Color(24, 252, 0));
        jpanelgradient_11.setColorStart(new java.awt.Color(0, 100, 0));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/okok-removebg-preview.png"))); // NOI18N

        pn_btnclose3.setBackground(new java.awt.Color(0, 153, 0));
        pn_btnclose3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_btnclose3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_btnclose3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_btnclose3MouseExited(evt);
            }
        });

        btnclose3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Izzul Islam Ramadhan\\Downloads\\close.png")); // NOI18N
        btnclose3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnclose3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnclose3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnclose3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_btnclose3Layout = new javax.swing.GroupLayout(pn_btnclose3);
        pn_btnclose3.setLayout(pn_btnclose3Layout);
        pn_btnclose3Layout.setHorizontalGroup(
            pn_btnclose3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnclose3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnclose3)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        pn_btnclose3Layout.setVerticalGroup(
            pn_btnclose3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnclose3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnclose3)
                .addGap(10, 10, 10))
        );

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Kasir1-removebg-preview.png"))); // NOI18N

        javax.swing.GroupLayout jpanelgradient_11Layout = new javax.swing.GroupLayout(jpanelgradient_11);
        jpanelgradient_11.setLayout(jpanelgradient_11Layout);
        jpanelgradient_11Layout.setHorizontalGroup(
            jpanelgradient_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelgradient_11Layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(32, 32, 32)
                .addComponent(pn_btnclose3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jpanelgradient_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpanelgradient_11Layout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(22, Short.MAX_VALUE)))
        );
        jpanelgradient_11Layout.setVerticalGroup(
            jpanelgradient_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelgradient_11Layout.createSequentialGroup()
                .addGroup(jpanelgradient_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelgradient_11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pn_btnclose3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelgradient_11Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel16)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpanelgradient_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpanelgradient_11Layout.createSequentialGroup()
                    .addGap(126, 126, 126)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(92, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpanelgradient_11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
            .addComponent(jpanelgradient_11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnloginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnloginMouseEntered
        // TODO add your handling code here:
        btnlogin.setForeground(new Color(0,51,153));
    }//GEN-LAST:event_btnloginMouseEntered

    private void btnloginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnloginMouseExited
        // TODO add your handling code here:
        btnlogin.setForeground(new Color(51,153,255));
    }//GEN-LAST:event_btnloginMouseExited

    private void btnloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnloginMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Login2().setVisible(true);
    }//GEN-LAST:event_btnloginMouseClicked

    private void btnsubmitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsubmitMouseEntered
        // TODO add your handling code here:
        btnsubmit.setBackground(new Color(0,102,0));
    }//GEN-LAST:event_btnsubmitMouseEntered

    private void btnsubmitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsubmitMouseExited
        // TODO add your handling code here:
        btnsubmit.setBackground(new Color(0,153,0));
    }//GEN-LAST:event_btnsubmitMouseExited

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        // TODO add your handling code here:
        if (txtnama.getText().equals("*Masukkan nama lengkap") || txtusername.getText().equals("*Masukkan username") || txtpassword.getText().equals("*Masukkan password") || txttelepon.getText().equals("*Masukkan nomor handphone")) {
        JOptionPane.showMessageDialog(this, "Silahkan isi data terlebih dahulu !");
        return;
        }
        try {
        String Username = txtusername.getText();
        String noTelepon = txttelepon.getText();

        String checkUsername = "SELECT COUNT(*) FROM akun WHERE username = ?";
        Connection connUsername = Config.configDB();
        PreparedStatement pstUsername = connUsername.prepareStatement(checkUsername);
        pstUsername.setString(1, Username);
        ResultSet rsUsername = pstUsername.executeQuery();
        rsUsername.next();

        int countUsername = rsUsername.getInt(1);

        if (countUsername > 0) {
            JOptionPane.showMessageDialog(this, "Akun dengan username '" + Username + "' sudah terdaftar. Silahkan buat username yg berbeda.");
        } else {
            String checkTelepon = "SELECT COUNT(*) FROM akun WHERE telp_user = ?";
            Connection connTelepon = Config.configDB();
            PreparedStatement pstTelepon = connTelepon.prepareStatement(checkTelepon);
            pstTelepon.setString(1, noTelepon);
            ResultSet rsTelepon = pstTelepon.executeQuery();
            rsTelepon.next();

        int countTelepon = rsTelepon.getInt(1);

        if (countTelepon > 0) {
            JOptionPane.showMessageDialog(this, "Akun dengan no. handphone '" + noTelepon + "' sudah ada. Gunakan nomor yang berbeda.");
        } else {
            String sql = "INSERT INTO akun VALUES ('"+txtusername.getText()+"','"+txtpassword.getText()+"','"+txtnama.getText()+"','"+txttelepon.getText()+"')";
            Connection conn= Config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
            this.setVisible(false);
            new Login2().setVisible(true);
        }
    }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void btncancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncancelMouseEntered
        // TODO add your handling code here:
        btncancel.setBackground(new Color(153,0,0));
    }//GEN-LAST:event_btncancelMouseEntered

    private void btncancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncancelMouseExited
        // TODO add your handling code here:
        btncancel.setBackground(new Color(204,0,0));
    }//GEN-LAST:event_btncancelMouseExited

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Login2().setVisible(true);
    }//GEN-LAST:event_btncancelActionPerformed

    private void btnclose3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclose3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnclose3MouseClicked

    private void btnclose3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclose3MouseEntered
        // TODO add your handling code here:
        pn_btnclose3.setBackground(new Color(255,0,0));
        btnclose3.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_btnclose3MouseEntered

    private void btnclose3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclose3MouseExited
        // TODO add your handling code here:
        pn_btnclose3.setBackground(new Color(0,153,0));
        btnclose3.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btnclose3MouseExited

    private void pn_btnclose3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnclose3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_pn_btnclose3MouseClicked

    private void pn_btnclose3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnclose3MouseEntered
        // TODO add your handling code here:
        pn_btnclose3.setBackground(new Color(255,0,0));
        btnclose3.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_pn_btnclose3MouseEntered

    private void pn_btnclose3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnclose3MouseExited
        // TODO add your handling code here:
        pn_btnclose3.setBackground(new Color(0,153,0));
        btnclose3.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_pn_btnclose3MouseExited

    private void txtpasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpasswordFocusGained
        // TODO add your handling code here:
        String user = txtpassword.getText();
        if (user.equals("*Masukkan password")) {
            txtpassword.setText("");
        }
    }//GEN-LAST:event_txtpasswordFocusGained

    private void txtpasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpasswordFocusLost
        // TODO add your handling code here:
        String user = txtpassword.getText();
        if (user.equals("") || user.equals("*Masukkan password")) {
            txtpassword.setText("*Masukkan password");
            txtpassword.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_txtpasswordFocusLost

    private void txtpasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpasswordMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordMouseClicked

    private void txtpasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpasswordMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordMousePressed

    private void txtpasswordMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpasswordMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordMouseReleased

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordActionPerformed

    private void txtpasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasswordKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordKeyPressed

    private void txtpasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasswordKeyTyped
        // TODO add your handling code here:
        txtpassword.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_txtpasswordKeyTyped

    private void txtusernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtusernameFocusGained
        // TODO add your handling code here:
        String user = txtusername.getText();
        if (user.equals("*Masukkan username")) {
            txtusername.setText("");
        }
    }//GEN-LAST:event_txtusernameFocusGained

    private void txtusernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtusernameFocusLost
        // TODO add your handling code here:
        String user = txtusername.getText();
        if (user.equals("") || user.equals("*Masukkan username")) {
            txtusername.setText("*Masukkan username");
            txtusername.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_txtusernameFocusLost

    private void txtusernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtusernameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameMouseClicked

    private void txtusernameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtusernameMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameMousePressed

    private void txtusernameMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtusernameMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameMouseReleased

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameActionPerformed

    private void txtusernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusernameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameKeyPressed

    private void txtusernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusernameKeyTyped
        // TODO add your handling code here:
        txtusername.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_txtusernameKeyTyped

    private void txtteleponFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtteleponFocusGained
        // TODO add your handling code here:
        String user = txttelepon.getText();
        if (user.equals("*Masukkan nomor handphone")) {
            txttelepon.setText("");
        }
    }//GEN-LAST:event_txtteleponFocusGained

    private void txtteleponFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtteleponFocusLost
        // TODO add your handling code here:
        String user = txttelepon.getText();
        if (user.equals("") || user.equals("*Masukkan nomor handphone")) {
            txttelepon.setText("*Masukkan nomor handphone");
            txttelepon.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_txtteleponFocusLost

    private void txtteleponMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtteleponMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtteleponMouseClicked

    private void txtteleponMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtteleponMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtteleponMousePressed

    private void txtteleponMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtteleponMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtteleponMouseReleased

    private void txtteleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtteleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtteleponActionPerformed

    private void txtteleponKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtteleponKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtteleponKeyPressed

    private void txtteleponKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtteleponKeyTyped
        // TODO add your handling code here:
        txttelepon.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_txtteleponKeyTyped

    private void txtnamaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnamaFocusGained
        // TODO add your handling code here:
        String user = txtnama.getText();
        if (user.equals("*Masukkan nama lengkap")) {
            txtnama.setText("");
        }
    }//GEN-LAST:event_txtnamaFocusGained

    private void txtnamaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnamaFocusLost
        // TODO add your handling code here:
        String user = txtnama.getText();
        if (user.equals("") || user.equals("*Masukkan nama lengkap")) {
            txtnama.setText("*Masukkan nama lengkap");
            txtnama.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_txtnamaFocusLost

    private void txtnamaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnamaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaMouseClicked

    private void txtnamaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnamaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaMousePressed

    private void txtnamaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnamaMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaMouseReleased

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void txtnamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnamaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaKeyPressed

    private void txtnamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnamaKeyTyped
        // TODO add your handling code here:
        txtnama.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_txtnamaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancel;
    private javax.swing.JLabel btnclose3;
    private javax.swing.JLabel btnlogin;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private jpanelgradient.jpanelgradient_1 jpanelgradient_11;
    private javax.swing.JPanel pn_btnclose3;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txttelepon;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
